[package]
name = "ingress-rpc-lib"
version.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
edition.workspace = true

[lints]
workspace = true

[dependencies]
url.workspace = true
op-revm.workspace = true
metrics.workspace = true
async-trait.workspace = true
base-cli-utils.workspace = true
metrics-derive.workspace = true
base-bundles.workspace = true
base-alloy-network.workspace = true
audit-archiver-lib.workspace = true
alloy-signer-local.workspace = true
reth-optimism-evm.workspace = true
reth-rpc-eth-types.workspace = true
uuid = { workspace = true, features = ["v5"] }
tokio = { workspace = true, features = ["full"] }
anyhow = { workspace = true, features = ["std"] }
tracing = { workspace = true, features = ["std"] }
moka = { workspace = true, features = ["future"] }
serde_json = { workspace = true, features = ["std"] }
alloy-consensus = { workspace = true, features = ["std"] }
alloy-provider = { workspace = true, features = ["reqwest"] }
backon = { workspace = true, features = ["std", "tokio-sleep"] }
clap = { workspace = true, features = ["std", "derive", "env"] }
jsonrpsee = { workspace = true, features = ["server", "macros"] }
axum = { workspace = true, features = ["tokio", "http1", "json"] }
alloy-primitives = { workspace = true, features = ["map-foldhash", "serde"] }
base-alloy-consensus = { workspace = true, features = ["std", "k256", "serde"] }
rdkafka = { workspace = true, features = ["tokio", "libz", "zstd", "ssl-vendored"] }

[dev-dependencies]
wiremock.workspace = true
base-bundles = { workspace = true, features = ["test-utils"] }
