[package]
name = "tips-ingress-rpc"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "tips-ingress-rpc"
path = "src/main.rs"

[dependencies]
tips-datastore.workspace = true
tips-audit.workspace = true
jsonrpsee.workspace = true
alloy-rpc-types-mev.workspace = true
alloy-primitives.workspace = true
op-alloy-network.workspace = true
alloy-provider.workspace = true
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
anyhow.workspace = true
clap.workspace = true
url.workspace = true
alloy-consensus.workspace = true
op-alloy-consensus.workspace = true
eyre.workspace = true
dotenvy.workspace = true
rdkafka.workspace = true
reth-rpc-eth-types.workspace = true
serde.workspace = true
serde_json.workspace = true
async-trait.workspace = true
backon.workspace = true
op-revm.workspace = true
revm-context-interface.workspace = true
alloy-signer-local.workspace = true
reth-optimism-evm.workspace = true
reth-errors.workspace = true
