[package]
name = "tips-ingress-rpc"
version.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
edition.workspace = true

[[bin]]
name = "tips-ingress-rpc"
path = "src/bin/main.rs"

[dependencies]
tips-core.workspace = true
tips-audit.workspace = true
account-abstraction-core.workspace = true
url.workspace = true
metrics.workspace = true
dotenvy.workspace = true
op-revm.workspace = true
async-trait.workspace = true
metrics-derive.workspace = true
alloy-primitives = { workspace = true, features = ["map-foldhash", "serde"] }
alloy-signer-local.workspace = true
op-alloy-network.workspace = true
reth-optimism-evm.workspace = true
reth-rpc-eth-types.workspace = true
tokio = { workspace = true, features = ["full"] }
tracing = { workspace = true, features = ["std"] }
anyhow = { workspace = true, features = ["std"] }
serde_json = { workspace = true, features = ["std"] }
axum = { workspace = true, features = ["tokio", "http1", "json"] }
rdkafka = { workspace = true, features = ["tokio", "libz"] }
backon = { workspace = true, features = ["std", "tokio-sleep"] }
jsonrpsee = { workspace = true, features = ["server", "macros"] }
alloy-consensus = { workspace = true, features = ["std"] }
alloy-provider = { workspace = true, features = ["reqwest"] }
op-alloy-consensus = { workspace = true, features = ["std", "k256", "serde"] }
clap = { version = "4.5.47", features = ["std", "derive", "env"] }

[dev-dependencies]
wiremock.workspace = true
mockall = "0.13"
jsonrpsee = { workspace = true, features = ["server", "http-client", "macros"] }