[package]
name = "base-client-cli"
description = "CLI argument types for Base node consensus clients"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[lints]
workspace = true

[dependencies]
# General
url.workspace = true
clap.workspace = true
eyre.workspace = true

# Alloy
alloy-chains.workspace = true

# Kona
kona-genesis.workspace = true
kona-registry.workspace = true

# Tracing
tracing.workspace = true

# Error Handling
thiserror.workspace = true
serde_json.workspace = true

# Base
base-jwt = { workspace = true, features = ["engine-validation"] }
