[package]
name = "base-client-cli"
description = "CLI argument types for Base node consensus clients"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[lints]
workspace = true

[dependencies]
# workspace
base-jwt = { workspace = true, features = ["engine-validation"] }

# consensus
base-consensus-rpc.workspace = true
base-consensus-disc.workspace = true
base-consensus-peers.workspace = true
base-consensus-derive.workspace = true
base-consensus-gossip.workspace = true
base-consensus-sources.workspace = true
base-consensus-genesis.workspace = true
base-consensus-registry.workspace = true
base-consensus-node.workspace = true
base-consensus-providers.workspace = true

# alloy
alloy-chains = { workspace = true, features = ["std"] }
alloy-signer.workspace = true
alloy-rpc-types-engine.workspace = true
alloy-provider.workspace = true
alloy-primitives.workspace = true
alloy-signer-local.workspace = true

# networking
reqwest.workspace = true
discv5 = { workspace = true, features = ["libp2p"] }
libp2p = { workspace = true, features = ["secp256k1", "macros", "tokio", "tcp", "noise", "gossipsub", "ping", "yamux", "identify"] }

# cli
url.workspace = true

# tokio
tokio.workspace = true

# tracing
tracing = { workspace = true, features = ["std"] }

# misc
eyre.workspace = true
thiserror = { workspace = true, features = ["std"] }
serde_json = { workspace = true, features = ["std"] }

