[package]
name = "base-txpool"
description = "Txpool extensions for Base"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[lints]
workspace = true

[dependencies]
# reth
reth.workspace = true
reth-exex.workspace = true
reth-tracing.workspace = true
reth-transaction-pool.workspace = true

# alloy
alloy-primitives.workspace = true

# rpc
jsonrpsee.workspace = true

# async
tokio.workspace = true
futures.workspace = true

# misc
lru.workspace = true
eyre.workspace = true
chrono.workspace = true
metrics.workspace = true
derive_more = { workspace = true, features = ["display"] }
tracing.workspace = true
serde.workspace = true

[dev-dependencies]
httpmock.workspace = true
serde_json.workspace = true
reth-transaction-pool = { workspace = true, features = ["test-utils"] }
