[package]
name = "base-txpool"
description = "Txpool extensions for Base"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[lints]
workspace = true

[dependencies]
# workspace
base-client-node.workspace = true
base-flashblocks.workspace = true

# reth
reth-tracing.workspace = true
reth-transaction-pool.workspace = true
reth-node-api.workspace = true
reth-primitives-traits.workspace = true
reth-provider.workspace = true

# alloy
alloy-primitives.workspace = true

# rpc
jsonrpsee.workspace = true

# async
tokio.workspace = true
tokio-stream.workspace = true
futures.workspace = true

# misc
lru.workspace = true
chrono.workspace = true
metrics.workspace = true
derive_more = { workspace = true, features = ["display"] }
tracing.workspace = true
serde.workspace = true
metrics-derive.workspace = true

[dev-dependencies]
eyre.workspace = true
httpmock.workspace = true
serde_json.workspace = true
reth-transaction-pool = { workspace = true, features = ["test-utils"] }
base-flashblocks = { workspace = true, features = ["test-utils"] }
alloy-consensus.workspace = true
alloy-eips.workspace = true
op-alloy-consensus.workspace = true
op-alloy-rpc-types.workspace = true
reth-optimism-primitives.workspace = true
revm-database.workspace = true
