[package]
name = "system-tests"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[lib]
path = "src/lib.rs"

[lints]
workspace = true

[dependencies]
hex.workspace = true
rand.workspace = true
dashmap.workspace = true
indicatif.workspace = true
rand_chacha.workspace = true
url = { workspace = true }
base-bundles.workspace = true
bytes = { workspace = true }
async-trait = { workspace = true }
audit-archiver-lib = { workspace = true }
alloy-network = { workspace = true }
base-alloy-network = { workspace = true }
alloy-signer-local = { workspace = true }
aws-credential-types = { workspace = true }
serde = { workspace = true, features = ["std", "derive"] }
tokio = { workspace = true, features = ["full"] }
tracing = { workspace = true, features = ["std"] }
anyhow = { workspace = true, features = ["std"] }
uuid = { workspace = true, features = ["v5", "serde"] }
serde_json = { workspace = true, features = ["std"] }
rdkafka = { workspace = true, features = ["tokio", "libz", "zstd", "ssl-vendored"] }
alloy-consensus = { workspace = true, features = ["std"] }
alloy-provider = { workspace = true, features = ["reqwest"] }
clap = { workspace = true, features = ["std", "derive", "env"] }
base-alloy-consensus = { workspace = true, features = ["std", "k256", "serde"] }
alloy-primitives = { workspace = true, features = ["map-foldhash", "serde"] }
tracing-subscriber = { workspace = true, features = ["std", "fmt", "env-filter", "json"] }
aws-sdk-s3 = { workspace = true, features = ["rustls", "default-https-client", "rt-tokio"] }

[dev-dependencies]
serial_test.workspace = true
tokio = { workspace = true, features = ["full", "test-util"] }
