[package]
name = "ingress-rpc"
version.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
edition.workspace = true

[[bin]]
name = "ingress-rpc"
path = "src/main.rs"

[lints]
workspace = true

[dependencies]
clap.workspace = true
tokio.workspace = true
anyhow.workspace = true
serde.workspace = true
tracing = { workspace = true, features = ["std"] }
dotenvy.workspace = true
rdkafka.workspace = true
jsonrpsee.workspace = true
alloy-provider.workspace = true
base-cli-utils.workspace = true
base-bundles.workspace = true
ingress-rpc-lib.workspace = true
base-alloy-network.workspace = true
audit-archiver-lib.workspace = true
