[package]
name = "base-execution-cli"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[lints]
workspace = true

[dependencies]
reth-cli.workspace = true
reth-cli-commands.workspace = true
reth-rpc-server-types.workspace = true
reth-db = { workspace = true, features = ["mdbx"] }
reth-provider.workspace = true
reth-node-core.workspace = true
base-node-core.workspace = true

# so jemalloc metrics can be included
reth-node-metrics.workspace = true

## optimism
base-execution-primitives.workspace = true
base-execution-chainspec.workspace = true
base-execution-consensus.workspace = true
base-execution-trie.workspace = true

reth-chainspec.workspace = true
reth-cli-runner.workspace = true
reth-node-builder.workspace = true
reth-tracing.workspace = true

# misc
futures.workspace = true
clap = { workspace = true, features = ["derive", "env"] }

tracing.workspace = true
eyre.workspace = true

# reth test-vectors
proptest = { workspace = true, optional = true }
base-alloy-consensus = { workspace = true, optional = true }

[dev-dependencies]
tempfile.workspace = true

[build-dependencies]
base-execution-chainspec = { workspace = true, features = ["std"] }

[features]
default = []

# Opentelemetry feature to activate tracing and logs export
otlp = [ "reth-node-core/otlp", "reth-tracing/otlp" ]
otlp-logs = [ "reth-node-core/otlp-logs", "reth-tracing/otlp-logs" ]

asm-keccak = [ "base-node-core/asm-keccak", "reth-node-core/asm-keccak" ]

keccak-cache-global = [
	"base-node-core/keccak-cache-global",
	"reth-node-core/keccak-cache-global",
]

# Jemalloc feature for vergen to generate correct env vars
jemalloc = [ "reth-node-core/jemalloc", "reth-node-metrics/jemalloc" ]
jemalloc-prof = [ "jemalloc", "reth-node-metrics/jemalloc-prof" ]
jemalloc-symbols = [ "jemalloc-prof", "reth-node-metrics/jemalloc-symbols" ]

tracy = [ "reth-node-core/tracy", "reth-tracing/tracy" ]

dev = [
	"base-alloy-consensus?/arbitrary",
	"dep:base-alloy-consensus",
	"dep:proptest",
	"reth-cli-commands/arbitrary",
]

serde = [
	"base-alloy-consensus?/serde",
	"base-execution-chainspec/serde",
	"base-execution-primitives/serde",
]

edge = [ "reth-cli-commands/edge", "reth-node-core/edge" ]
