[workspace.package]
version = "0.2.1"
edition = "2024"
rust-version = "1.88"
license = "MIT"
homepage = "https://github.com/base/node-reth"
repository = "https://github.com/base/node-reth"

[workspace]
resolver = "2"
members = ["bin/*", "crates/client/*", "crates/shared/*"]
default-members = ["bin/node"]

[workspace.metadata.cargo-udeps.ignore]
normal = ["rustls-platform-verifier"]

[workspace.lints.rust]
missing-debug-implementations = "warn"
missing-docs = "warn"
unreachable-pub = "warn"
unused-must-use = "deny"
rust-2018-idioms = "deny"
unnameable-types = "warn"

[workspace.lints.rustdoc]
all = "warn"

[workspace.lints.clippy]
all = { level = "warn", priority = -1 }
missing-const-for-fn = "warn"
use-self = "warn"
option-if-let-else = "warn"
redundant-clone = "warn"

[profile.dev]
debug = "line-tables-only"
split-debuginfo = "unpacked"

[profile.release]
opt-level = 3
lto = "thin"
debug = "none"
strip = "symbols"
panic = "unwind"
codegen-units = 16

[profile.maxperf]
inherits = "release"
lto = "fat"
codegen-units = 1

[workspace.dependencies]
# Shared
base-access-lists = { path = "crates/shared/access-lists" }
base-flashtypes = { path = "crates/shared/flashtypes" }
base-cli-utils = { path = "crates/shared/cli-utils" }
# Client
base-primitives = { path = "crates/client/primitives" }
base-bundles = { path = "crates/shared/bundles" }
base-reth-metering = { path = "crates/client/metering" }
base-reth-rpc-types = { path = "crates/client/reth-rpc-types" }
base-txpool = { path = "crates/client/txpool" }
base-reth-runner = { path = "crates/client/runner" }
base-reth-test-utils = { path = "crates/client/test-utils" }
base-reth-flashblocks = { path = "crates/client/flashblocks" }

# reth
reth = { git = "https://github.com/paradigmxyz/reth", tag = "v1.9.3" }
reth-ipc = { git = "https://github.com/paradigmxyz/reth", tag = "v1.9.3" }
reth-evm = { git = "https://github.com/paradigmxyz/reth", tag = "v1.9.3" }
reth-exex = { git = "https://github.com/paradigmxyz/reth", tag = "v1.9.3" }
reth-tracing = { git = "https://github.com/paradigmxyz/reth", tag = "v1.9.3" }
reth-cli-util = { git = "https://github.com/paradigmxyz/reth", tag = "v1.9.3" }
reth-provider = { git = "https://github.com/paradigmxyz/reth", tag = "v1.9.3" }
reth-db-common = { git = "https://github.com/paradigmxyz/reth", tag = "v1.9.3" }
reth-rpc-layer = { git = "https://github.com/paradigmxyz/reth", tag = "v1.9.3" }
reth-node-core = { git = "https://github.com/paradigmxyz/reth", tag = "v1.9.3" }
reth-primitives = { git = "https://github.com/paradigmxyz/reth", tag = "v1.9.3" }
reth-rpc = { git = "https://github.com/paradigmxyz/reth", tag = "v1.9.3" }
reth-rpc-eth-api = { git = "https://github.com/paradigmxyz/reth", tag = "v1.9.3" }
reth-rpc-convert = { git = "https://github.com/paradigmxyz/reth", tag = "v1.9.3" }
reth-optimism-cli = { git = "https://github.com/paradigmxyz/reth", tag = "v1.9.3" }
reth-optimism-rpc = { git = "https://github.com/paradigmxyz/reth", tag = "v1.9.3" }
reth-optimism-evm = { git = "https://github.com/paradigmxyz/reth", tag = "v1.9.3" }
reth-testing-utils = { git = "https://github.com/paradigmxyz/reth", tag = "v1.9.3" }
reth-optimism-node = { git = "https://github.com/paradigmxyz/reth", tag = "v1.9.3" }
reth-e2e-test-utils = { git = "https://github.com/paradigmxyz/reth", tag = "v1.9.3" }
reth-transaction-pool = { git = "https://github.com/paradigmxyz/reth", tag = "v1.9.3" }
reth-rpc-eth-types = { git = "https://github.com/paradigmxyz/reth", tag = "v1.9.3" }
reth-primitives-traits = { git = "https://github.com/paradigmxyz/reth", tag = "v1.9.3" }
reth-optimism-chainspec = { git = "https://github.com/paradigmxyz/reth", tag = "v1.9.3" }
reth-optimism-primitives = { git = "https://github.com/paradigmxyz/reth", tag = "v1.9.3" }
reth-optimism-payload-builder = { git = "https://github.com/paradigmxyz/reth", tag = "v1.9.3" }
reth-db = { git = "https://github.com/paradigmxyz/reth", tag = "v1.9.3", features = [
    "op",
] }

# revm
revm = { version = "31.0.2", default-features = false }
revm-bytecode = { version = "7.1.1", default-features = false }

# alloy
alloy-rlp = "0.3.10"
alloy-trie = "0.9.1"
alloy-eips = "1.0.41"
alloy-serde = "1.0.41"
alloy-eip7928 = "0.3.0"
alloy-genesis = "1.0.41"
alloy-signer-local = "1.0.41"
alloy-hardforks = "0.4.4"
alloy-provider = "1.0.41"
alloy-contract = "1.0.41"
alloy-sol-types = "1.4.1"
alloy-sol-macro = "1.4.1"
alloy-primitives = "1.4.1"
alloy-consensus = "1.0.41"
alloy-rpc-types = "1.0.41"
alloy-rpc-client = "1.0.41"
alloy-rpc-types-eth = "1.0.41"
alloy-rpc-types-engine = "1.0.41"

# op-alloy
op-alloy-flz = "0.13.1"
op-alloy-network = "0.22.0"
op-alloy-rpc-types = "0.22.0"
op-alloy-consensus = "0.22.0"
op-alloy-rpc-jsonrpsee = "0.22.0"
op-alloy-rpc-types-engine = "0.22.0"
alloy-op-evm = { version = "0.23.3", default-features = false }

# op-revm
op-revm = { version = "12.0.2", default-features = false }

# tokio
tokio = "1.48.0"
tokio-stream = "0.1.17"
tokio-tungstenite = { version = "0.28.0", features = ["native-tls"] }

# async
futures = "0.3.31"
reqwest = "0.12.25"
futures-util = "0.3.31"

# rpc
jsonrpsee = "0.26.0"
jsonrpsee-types = "0.26.0"

# misc
url = "2.5.7"
lru = "0.16.2"
parking_lot = "0.12.4"
indexmap = "2.4.0"
rand = "0.9.2"
uuid = "1.19.0"
time = "0.3.44"
rayon = "1.11"
clap = "4.5.53"
eyre = "0.6.12"
bytes = "1.11.0"
brotli = "8.0.2"
chrono = "0.4.42"
rstest = "0.26.1"
serde = "1.0.228"
rustls = "0.23.35"
httpmock = "0.8.2"
tracing = "0.1.43"
metrics = "0.24.3"
arc-swap = "1.7.1"
once_cell = "1.21.3"
itertools = "0.14.0"
derive_more = "2.1.0"
serde_json = "1.0.145"
metrics-derive = "0.1.0"
tracing-subscriber = "0.3.22"
thiserror = "2.0"
