[workspace.package]
version = "0.1.0"
edition = "2021"
rust-version = "1.85"
license = "MIT"
homepage = "https://github.com/base/reth"
repository = "https://github.com/base/reth"

[workspace]
resolver = "2"
members = ["crates/flashblocks-rpc", "crates/node"]

default-members = ["crates/node"]

[workspace.lints]

[workspace.dependencies]
# internal
base-reth-flashblocks-rpc = { path = "crates/flashblocks-rpc" }
base-reth-node = { path = "crates/node" }

# reth
reth = { git = "https://github.com/paradigmxyz/reth", tag = "v1.5.0" }
reth-optimism-node = { git = "https://github.com/paradigmxyz/reth", tag = "v1.5.0" }
reth-optimism-cli = { git = "https://github.com/paradigmxyz/reth", tag = "v1.5.0" }
reth-primitives = { git = "https://github.com/paradigmxyz/reth", tag = "v1.5.0" }
reth-rpc-eth-api = { git = "https://github.com/paradigmxyz/reth", tag = "v1.5.0" }
reth-optimism-primitives = { git = "https://github.com/paradigmxyz/reth", tag = "v1.5.0" }
reth-rpc-convert = { git = "https://github.com/paradigmxyz/reth", tag = "v1.5.0" }
reth-optimism-rpc = { git = "https://github.com/paradigmxyz/reth", tag = "v1.5.0" }
reth-optimism-evm = { git = "https://github.com/paradigmxyz/reth", tag = "v1.5.0" }
reth-optimism-chainspec = { git = "https://github.com/paradigmxyz/reth", tag = "v1.5.0" }

# revm
revm = { version = "26.0.1", default-features = false }
revm-bytecode = { version = "5.0.0", default-features = false }

# alloy
alloy-primitives = { version = "1.2.0", default-features = false, features = [
    "map-foldhash",
] }
alloy-eips = { version = "1.0.16", default-features = false }
alloy-rpc-types = { version = "1.0.16", default-features = false }
alloy-rpc-types-engine = { version = "1.0.16", default-features = false }
alloy-rpc-types-eth = { version = "1.0.16" }
alloy-consensus = { version = "1.0.16" }
alloy-trie = { version = "0.9.0", default-features = false }
nybbles = { version = "0.4.0", default-features = false }
alloy-provider = { version = "1.0.16" }
alloy-hardforks = "0.2.7"

# op-alloy
op-alloy-rpc-types = { version = "0.18.7", default-features = false }
op-alloy-rpc-types-engine = { version = "0.18.7", default-features = false }
op-alloy-rpc-jsonrpsee = { version = "0.18.7", default-features = false }
op-alloy-network = { version = "0.18.7", default-features = false }
op-alloy-consensus = { version = "0.18.7", default-features = false }

# rollup-boost
rollup-boost = { git = "http://github.com/flashbots/rollup-boost", rev = "4f6c93ed1ecd9131cea14213368f3393dbade46a" }
rustls = "0.23.23"

# tokio
tokio = { version = "1.44.2", features = ["full"] }
tokio-stream = "0.1.11"
tokio-tungstenite = { version = "0.26.2", features = ["native-tls"] }

# async
futures = "0.3"
futures-util = "0.3"
reqwest = { version = "0.12", features = ["json", "stream"] }

# rpc
jsonrpsee = { version = "0.25.1" }

# misc
clap = { version = "4.4.3" }
tracing = { version = "0.1.41" }
serde = "1"
serde_json = "1.0"
url = "2.5"
metrics = "0.24.1"
metrics-derive = "0.1"
itertools = "0.14"
eyre = { version = "0.6.12" }
uuid = { version = "1.6.1", features = ["serde", "v5", "v4"] }
time = { version = "0.3.36", features = ["macros", "formatting", "parsing"] }
chrono = "0.4"
brotli = "8.0.1"
