[workspace.package]
version = "0.0.0"
edition = "2024"
rust-version = "1.88"
license = "MIT"
homepage = "https://github.com/base/node-reth"
repository = "https://github.com/base/node-reth"
exclude = [".github/"]

[workspace]
resolver = "2"
members = ["bin/*", "crates/client/*", "crates/shared/*", "crates/builder/*"]
default-members = ["bin/node", "bin/consensus"]

[workspace.metadata.cargo-udeps.ignore]
normal = ["rustls-platform-verifier"]

[workspace.lints.rust]
missing-debug-implementations = "warn"
missing-docs = "warn"
unreachable-pub = "warn"
unused-must-use = "deny"
rust-2018-idioms = "deny"
unnameable-types = "warn"

[workspace.lints.rustdoc]
all = "warn"

[workspace.lints.clippy]
all = { level = "warn", priority = -1 }
missing-const-for-fn = "warn"
use-self = "warn"
option-if-let-else = "warn"
redundant-clone = "warn"

[profile.dev]
debug = "line-tables-only"
split-debuginfo = "packed"
incremental = false

[profile.release]
opt-level = 3
lto = "thin"
debug = "none"
strip = "symbols"
panic = "unwind"
codegen-units = 16

[profile.maxperf]
inherits = "release"
lto = "fat"
codegen-units = 1

[workspace.dependencies]
# Shared
base-bundles = { path = "crates/shared/bundles" }
base-cli-utils = { path = "crates/shared/cli-utils" }
base-flashtypes = { path = "crates/shared/flashtypes" }
base-primitives = { path = "crates/shared/primitives" }
base-access-lists = { path = "crates/shared/access-lists" }
base-reth-rpc-types = { path = "crates/shared/reth-rpc-types" }
base-jwt = { path = "crates/shared/jwt" }
base-flashblocks-node = { path = "crates/client/flashblocks-node" }

# Client
base-client-cli = { path = "crates/client/cli" }
base-client-engine = { path = "crates/client/engine" }
base-client-node = { path = "crates/client/node" }
base-metering = { path = "crates/client/metering" }
base-txpool = { path = "crates/client/txpool" }
base-flashblocks = { path = "crates/client/flashblocks" }

# Builder
base-builder-cli = { path = "crates/builder/base-builder-cli" }
op-rbuilder = { path = "crates/builder/op-rbuilder" }

# Kona
kona-rpc = { git = "https://github.com/ethereum-optimism/optimism", rev = "beda60f12100ae5f203b6199996dbb13a9daa7aa" }
kona-disc = { git = "https://github.com/ethereum-optimism/optimism", rev = "beda60f12100ae5f203b6199996dbb13a9daa7aa" }
kona-engine = { git = "https://github.com/ethereum-optimism/optimism", rev = "beda60f12100ae5f203b6199996dbb13a9daa7aa" }
kona-derive = { git = "https://github.com/ethereum-optimism/optimism", rev = "beda60f12100ae5f203b6199996dbb13a9daa7aa" }
kona-gossip = { git = "https://github.com/ethereum-optimism/optimism", rev = "beda60f12100ae5f203b6199996dbb13a9daa7aa" }
kona-genesis = { git = "https://github.com/ethereum-optimism/optimism", rev = "beda60f12100ae5f203b6199996dbb13a9daa7aa" }
kona-registry = { git = "https://github.com/ethereum-optimism/optimism", rev = "beda60f12100ae5f203b6199996dbb13a9daa7aa" }
kona-node-service = { git = "https://github.com/ethereum-optimism/optimism", rev = "beda60f12100ae5f203b6199996dbb13a9daa7aa" }
kona-providers-alloy = { git = "https://github.com/ethereum-optimism/optimism", rev = "beda60f12100ae5f203b6199996dbb13a9daa7aa" }
kona-cli = { git = "https://github.com/ethereum-optimism/optimism", rev = "beda60f12100ae5f203b6199996dbb13a9daa7aa", default-features = false, features = ["secrets"] }
kona-peers = { git = "https://github.com/ethereum-optimism/optimism", rev = "beda60f12100ae5f203b6199996dbb13a9daa7aa" }
kona-sources = { git = "https://github.com/ethereum-optimism/optimism", rev = "beda60f12100ae5f203b6199996dbb13a9daa7aa" }

# reth
reth-ipc = { git = "https://github.com/paradigmxyz/reth", tag = "v1.10.0" }
reth-evm = { git = "https://github.com/paradigmxyz/reth", tag = "v1.10.0" }
reth-exex = { git = "https://github.com/paradigmxyz/reth", tag = "v1.10.0" }
reth-tracing = { git = "https://github.com/paradigmxyz/reth", tag = "v1.10.0" }
reth-cli = { git = "https://github.com/paradigmxyz/reth", tag = "v1.10.0" }
reth-cli-commands = { git = "https://github.com/paradigmxyz/reth", tag = "v1.10.0" }
reth-cli-util = { git = "https://github.com/paradigmxyz/reth", tag = "v1.10.0" }
reth-provider = { git = "https://github.com/paradigmxyz/reth", tag = "v1.10.0" }
reth-db-common = { git = "https://github.com/paradigmxyz/reth", tag = "v1.10.0" }
reth-rpc-layer = { git = "https://github.com/paradigmxyz/reth", tag = "v1.10.0" }
reth-node-core = { git = "https://github.com/paradigmxyz/reth", tag = "v1.10.0" }
reth-primitives = { git = "https://github.com/paradigmxyz/reth", tag = "v1.10.0" }
reth-rpc = { git = "https://github.com/paradigmxyz/reth", tag = "v1.10.0" }
reth-rpc-eth-api = { git = "https://github.com/paradigmxyz/reth", tag = "v1.10.0" }
reth-rpc-convert = { git = "https://github.com/paradigmxyz/reth", tag = "v1.10.0" }
reth-rpc-api = { git = "https://github.com/paradigmxyz/reth", tag = "v1.10.0" }
reth-optimism-cli = { git = "https://github.com/paradigmxyz/reth", tag = "v1.10.0" }
reth-optimism-rpc = { git = "https://github.com/paradigmxyz/reth", tag = "v1.10.0", features = [
    "client",
] }
reth-consensus = { git = "https://github.com/paradigmxyz/reth", tag = "v1.10.0" }
reth-engine-primitives = { git = "https://github.com/paradigmxyz/reth", tag = "v1.10.0" }
reth-engine-tree = { git = "https://github.com/paradigmxyz/reth", tag = "v1.10.0" }
reth-rpc-builder = { git = "https://github.com/paradigmxyz/reth", tag = "v1.10.0" }
reth-tokio-util = { git = "https://github.com/paradigmxyz/reth", tag = "v1.10.0" }
reth-optimism-evm = { git = "https://github.com/paradigmxyz/reth", tag = "v1.10.0" }
reth-testing-utils = { git = "https://github.com/paradigmxyz/reth", tag = "v1.10.0" }
reth-optimism-node = { git = "https://github.com/paradigmxyz/reth", tag = "v1.10.0" }
reth-e2e-test-utils = { git = "https://github.com/paradigmxyz/reth", tag = "v1.10.0" }
reth-transaction-pool = { git = "https://github.com/paradigmxyz/reth", tag = "v1.10.0" }
reth-rpc-eth-types = { git = "https://github.com/paradigmxyz/reth", tag = "v1.10.0" }
reth-primitives-traits = { git = "https://github.com/paradigmxyz/reth", tag = "v1.10.0" }
reth-optimism-chainspec = { git = "https://github.com/paradigmxyz/reth", tag = "v1.10.0" }
reth-optimism-primitives = { git = "https://github.com/paradigmxyz/reth", tag = "v1.10.0" }
reth-db = { git = "https://github.com/paradigmxyz/reth", tag = "v1.10.0", features = [
    "op",
] }
reth-chain-state = { git = "https://github.com/paradigmxyz/reth", tag = "v1.10.0" }
reth-errors = { git = "https://github.com/paradigmxyz/reth", tag = "v1.10.0" }
reth-payload-builder = { git = "https://github.com/paradigmxyz/reth", tag = "v1.10.0" }
reth-node-api = { git = "https://github.com/paradigmxyz/reth", tag = "v1.10.0" }
reth-rpc-engine-api = { git = "https://github.com/paradigmxyz/reth", tag = "v1.10.0" }
reth-node-ethereum = { git = "https://github.com/paradigmxyz/reth", tag = "v1.10.0" }
reth-trie = { git = "https://github.com/paradigmxyz/reth", tag = "v1.10.0" }
reth-trie-common = { git = "https://github.com/paradigmxyz/reth", tag = "v1.10.0" }
reth-trie-parallel = { git = "https://github.com/paradigmxyz/reth", tag = "v1.10.0" }
reth-basic-payload-builder = { git = "https://github.com/paradigmxyz/reth", tag = "v1.10.0" }
reth-chainspec = { git = "https://github.com/paradigmxyz/reth", tag = "v1.10.0" }
reth-storage-api = { git = "https://github.com/paradigmxyz/reth", tag = "v1.10.0" }
reth-evm-ethereum = { git = "https://github.com/paradigmxyz/reth", tag = "v1.10.0" }
reth-execution-errors = { git = "https://github.com/paradigmxyz/reth", tag = "v1.10.0" }
reth-tasks = { git = "https://github.com/paradigmxyz/reth", tag = "v1.10.0" }
reth-metrics = { git = "https://github.com/paradigmxyz/reth", tag = "v1.10.0" }
reth-trie-db = { git = "https://github.com/paradigmxyz/reth", tag = "v1.10.0" }
reth-payload-primitives = { git = "https://github.com/paradigmxyz/reth", tag = "v1.10.0" }
reth-execution-types = { git = "https://github.com/paradigmxyz/reth", tag = "v1.10.0" }
reth-revm = { git = "https://github.com/paradigmxyz/reth", tag = "v1.10.0" }
reth-payload-builder-primitives = { git = "https://github.com/paradigmxyz/reth", tag = "v1.10.0" }
reth-payload-util = { git = "https://github.com/paradigmxyz/reth", tag = "v1.10.0" }
reth-network-peers = { git = "https://github.com/paradigmxyz/reth", tag = "v1.10.0" }
reth-node-builder = { git = "https://github.com/paradigmxyz/reth", tag = "v1.10.0" }
reth-tracing-otlp = { git = "https://github.com/paradigmxyz/reth", tag = "v1.10.0" }
reth-optimism-consensus = { git = "https://github.com/paradigmxyz/reth", tag = "v1.10.0" }
reth-optimism-forks = { git = "https://github.com/paradigmxyz/reth", tag = "v1.10.0" }
reth-optimism-payload-builder = { git = "https://github.com/paradigmxyz/reth", tag = "v1.10.0" }
reth-optimism-txpool = { git = "https://github.com/paradigmxyz/reth", tag = "v1.10.0" }
reth-optimism-storage = { git = "https://github.com/paradigmxyz/reth", tag = "v1.10.0" }
reth-rpc-server-types = { git = "https://github.com/paradigmxyz/reth", tag = "v1.10.0" }
reth-engine-local = { git = "https://github.com/paradigmxyz/reth", tag = "v1.10.0" }

# revm
revm = { version = "33.1.0", features = [
    "std",
    "secp256k1",
    "optional_balance_check",
], default-features = false }
revm-bytecode = { version = "7.1.1", default-features = false }
revm-inspectors = { version = "0.33.2", default-features = false }
revm-database = { version = "9.0.5", default-features = false }
revm-state = { version = "8.1.1", default-features = false }
revm-primitives = { version = "21.0.2", default-features = false }
revm-interpreter = { version = "31.1.0", default-features = false }
revm-database-interface = { version = "8.0.5", default-features = false }

# alloy
alloy-rlp = "0.3.10"
alloy-trie = "0.9.1"
alloy-eips = "1.4.3"
alloy-serde = "1.4.3"
alloy-eip7928 = "0.1.0"
alloy-genesis = "1.4.3"
alloy-signer = "1.4.3"
alloy-signer-local = "1.4.3"
alloy-hardforks = "0.4.5"
alloy-provider = { version = "1.4.3", features = [
    "ipc",
    "pubsub",
    "txpool-api",
    "engine-api",
] }
alloy-contract = "1.4.3"
alloy-sol-types = { version = "1.5.0", features = ["json"] }
alloy-sol-macro = "1.5.0"
alloy-primitives = { version = "1.5.0", default-features = false, features = [
    "map-foldhash",
] }
alloy-consensus = { version = "1.4.3", features = ["kzg"] }
alloy-rpc-types = "1.4.3"
alloy-rpc-client = "1.4.3"
alloy-rpc-types-eth = "1.4.3"
alloy-rpc-types-engine = { version = "1.4.3", features = ["ssz"] }
alloy-chains = "0.2.5"
alloy-evm = { version = "0.25.1", default-features = false }
alloy-pubsub = "1.4.3"
alloy-json-rpc = "1.4.3"
alloy-transport-http = "1.4.3"
alloy-network = "1.4.3"
alloy-network-primitives = "1.4.3"
alloy-transport = "1.4.3"
alloy-node-bindings = "1.4.3"
alloy-rpc-types-beacon = { version = "1.4.3", features = ["ssz"] }

# op-alloy
op-alloy-flz = { version = "0.13.1", default-features = false }
op-alloy-network = { version = "0.23.1", default-features = false }
op-alloy-provider = { version = "0.23.1", default-features = false }
op-alloy-rpc-types = { version = "0.23.1", default-features = false }
op-alloy-consensus = { version = "0.23.1", default-features = false }
op-alloy-rpc-jsonrpsee = { version = "0.23.1", default-features = false }
op-alloy-rpc-types-engine = { version = "0.23.1", default-features = false }
alloy-op-evm = { version = "0.25.0", default-features = false }
alloy-op-hardforks = "0.4.4"

# rollup-boost
rollup-boost = { git = "https://github.com/flashbots/rollup-boost", tag = "v0.7.11" }
# rollup-boost version that matches kona's dependency (used for consensus binary)
rollup-boost-kona = { package = "rollup-boost", git = "https://github.com/flashbots/rollup-boost.git", rev = "7fda98f" }


# op-revm
op-revm = { version = "14.1.0", default-features = false }

# tokio
tokio = "1.48.0"
tokio-stream = "0.1.17"
tokio-tungstenite = { version = "0.28.0", features = ["native-tls"] }

# async
futures = "0.3.31"
reqwest = "0.12.25"
futures-util = "0.3.31"

# rpc
jsonrpsee = "0.26.0"
jsonrpsee-types = "0.26.0"

# cli
vergen = "9.0.6"
vergen-git2 = "1.0.7"
clap = { version = "4.5.53", features = ["derive", "env", "string"] }

# Tracing
tracing = "0.1.43"
tracing-appender = "0.2.4"
tracing-subscriber = "0.3.22"

# Metrics
metrics = { version = "0.24.3", default-features = false }
prometheus = { version = "0.14.0", default-features = false }
metrics-process = { version = "2.4.2", default-features = false }
metrics-exporter-prometheus = { version = "0.18.1", default-features = false }

# misc
anyhow = "1"
url = "2.5.7"
lru = "0.16.3"
rand = "0.9.2"
shellexpand = "3.1"
strum = "0.27.2"
backon = "1.6.0"
uuid = "1.19.0"
time = { version = "0.3.44", features = ["macros", "formatting", "parsing"] }
rayon = "1.11"
clap_builder = "4.5.19"
eyre = "0.6.12"
bytes = "1.11.0"
brotli = "8.0.2"
chrono = "0.4.42"
rstest = "0.26.1"
serde = "1.0.228"
rustls = "0.23.35"
httpmock = "0.8.2"
arc-swap = "1.7.1"
once_cell = "1.21.3"
itertools = "0.14.0"
derive_more = "2.1.0"
serde_json = "1.0.145"
metrics-derive = "0.1.0"
thiserror = "2.0"
async-trait = "0.1.83"
parking_lot = "0.12.3"
auto_impl = "1.2.0"
serde_with = "3.8.1"
secp256k1 = "0.30"
libp2p = "0.56.0"
libp2p-identity = "0.2.12"
discv5 = "0.10"
either = { version = "1.15.0", default-features = false }
tokio-util = { version = "0.7.4", features = ["codec"] }
warp = "0.3.7"
flate2 = "1.0.37"
ctor = "0.4.2"
dashmap = "6.1"
hex = "0.4"
lazy_static = "1.4.0"
tikv-jemallocator = "0.6"
ahash = "0.8.6"
opentelemetry = { version = "0.31", features = ["trace"] }
jsonrpsee-core = "0.26.0"
ethereum_ssz = "0.9.0"
ethereum_ssz_derive = "0.9.0"
concurrent-queue = "2.5.0"
tower = "0.5"
moka = { version = "0.12", features = ["future"] }
http = "1.0"
sha3 = "0.10"
k256 = "0.13.4"
nanoid = "0.4"
tar = "0.4"
rlimit = "0.10"
hyper = { version = "1.7.0", features = ["http1"] }
hyper-util = "0.1.11"
http-body-util = "0.1.3"
testcontainers = "0.24.0"
dirs-next = "2.0.0"
tempfile = "3.8"
