[workspace.package]
version = "0.1.0"
edition = "2021"
rust-version = "1.85"
license = "MIT"
homepage = "https://github.com/base/node-reth"
repository = "https://github.com/base/node-reth"

[workspace]
resolver = "2"
members = ["crates/flashblocks-rpc", "crates/node", "crates/transaction-tracing"]

default-members = ["crates/node"]

[workspace.lints]

[profile.dev]
debug = "line-tables-only"
split-debuginfo = "unpacked"

[profile.release]
opt-level = 3
lto = "thin"
debug = "none"
strip = "symbols"
panic = "unwind"
codegen-units = 16

[profile.maxperf]
inherits = "release"
lto = "fat"
codegen-units = 1

[workspace.dependencies]
# internal
base-reth-flashblocks-rpc = { path = "crates/flashblocks-rpc" }
base-reth-node = { path = "crates/node" }
base-reth-transaction-tracing = { path = "crates/transaction-tracing" }

# reth
reth = { git = "https://github.com/paradigmxyz/reth", tag = "v1.8.1" }
reth-optimism-node = { git = "https://github.com/paradigmxyz/reth", tag = "v1.8.1" }
reth-optimism-cli = { git = "https://github.com/paradigmxyz/reth", tag = "v1.8.1" }
reth-primitives = { git = "https://github.com/paradigmxyz/reth", tag = "v1.8.1" }
reth-rpc-eth-api = { git = "https://github.com/paradigmxyz/reth", tag = "v1.8.1" }
reth-optimism-primitives = { git = "https://github.com/paradigmxyz/reth", tag = "v1.8.1" }
reth-rpc-convert = { git = "https://github.com/paradigmxyz/reth", tag = "v1.8.1" }
reth-optimism-rpc = { git = "https://github.com/paradigmxyz/reth", tag = "v1.8.1" }
reth-optimism-evm = { git = "https://github.com/paradigmxyz/reth", tag = "v1.8.1" }
reth-optimism-chainspec = { git = "https://github.com/paradigmxyz/reth", tag = "v1.8.1" }
reth-provider = { git = "https://github.com/paradigmxyz/reth", tag = "v1.8.1" }
reth-tracing = { git = "https://github.com/paradigmxyz/reth", tag = "v1.8.1" }
reth-e2e-test-utils = { git = "https://github.com/paradigmxyz/reth", tag = "v1.8.1" }
reth-primitives-traits = { git = "https://github.com/paradigmxyz/reth", tag = "v1.8.1" }
reth-evm = { git = "https://github.com/paradigmxyz/reth", tag = "v1.8.1" }
reth-cli-util = { git = "https://github.com/paradigmxyz/reth", tag = "v1.8.1" }
reth-exex = { git = "https://github.com/paradigmxyz/reth", tag = "v1.8.1" }
reth-db = { git = "https://github.com/paradigmxyz/reth", tag = "v1.8.1" }
reth-testing-utils = { git = "https://github.com/paradigmxyz/reth", tag = "v1.8.1" }
reth-db-common = { git = "https://github.com/paradigmxyz/reth", tag = "v1.8.1" }

# revm
revm = { version = "29.0.0", default-features = false }
revm-bytecode = { version = "6.2.2", default-features = false }

# alloy
alloy-primitives = { version = "1.3.1", default-features = false, features = [
    "map-foldhash",
] }
alloy-genesis = { version = "1.0.35", default-features = false }
alloy-eips = { version = "1.0.35", default-features = false }
alloy-rpc-types = { version = "1.0.35", default-features = false }
alloy-rpc-types-engine = { version = "1.0.35", default-features = false }
alloy-rpc-types-eth = { version = "1.0.35" }
alloy-consensus = { version = "1.0.35" }
alloy-trie = { version = "0.9.1", default-features = false }
alloy-provider = { version = "1.0.35" }
alloy-hardforks = "0.3.5"
alloy-rpc-client = { version = "1.0.35" }

# op-alloy
op-alloy-rpc-types = { version = "0.20.0", default-features = false }
op-alloy-rpc-types-engine = { version = "0.20.0", default-features = false }
op-alloy-rpc-jsonrpsee = { version = "0.20.0", default-features = false }
op-alloy-network = { version = "0.20.0", default-features = false }
op-alloy-consensus = { version = "0.20.0", default-features = false }

# rollup-boost
rollup-boost = { git = "http://github.com/flashbots/rollup-boost", rev = "98fff8e059870d192739dd42d41f5244c49f4b9c" }
rustls = "0.23.23"

# tokio
tokio = { version = "1.44.2", features = ["full"] }
tokio-stream = "0.1.11"
tokio-tungstenite = { version = "0.26.2", features = ["native-tls"] }

# async
futures = "0.3"
futures-util = "0.3"
reqwest = { version = "0.12", features = ["json", "stream"] }

# rpc
jsonrpsee = "0.26.0"
jsonrpsee-types = "0.26.0"

# misc
clap = { version = "4.4.3" }
tracing = { version = "0.1.41" }
serde = "1"
serde_json = "1.0"
url = "2.5"
metrics = "0.24.1"
metrics-derive = "0.1"
itertools = "0.14"
eyre = { version = "0.6.12" }
uuid = { version = "1.6.1", features = ["serde", "v5", "v4"] }
time = { version = "0.3.36", features = ["macros", "formatting", "parsing"] }
chrono = "0.4.41"
brotli = "8.0.1"
arc-swap = "1.7.1"
once_cell = "1.19"
rand = "0.9.2"