allow-dbg-in-tests = true
allow-print-in-tests = true
too-large-for-stack = 256
allowed-wildcard-imports = ["rayon::prelude", "ratatui::prelude", "httpmock::prelude", "super::*"]
doc-valid-idents = [
    "L1",
    "L2",
    "RPC",
    "EVM",
    "EIP",
    "Flashblocks",
    "Reth",

    "geth",
    "SSZ",
    "JWT",
    "API",
    "URL",
    "URI",
    "HTTP",
    "HTTPS",
    "WebSocket",
    "JSON",
    "MEV",
    "OP",
    "Optimism",
]
