verbose = "debug"
no_progress = false
exclude_all_private = false
accept = [200, 403] # 403 status code is often returned by private repos instead of 404
exclude_path = [
    "shared/primitives/contracts/lib"
]
exclude = [
    'foo.bar',
    'localhost',
    'https://img.shields.io/github/commit-activity/w/base/node-reth',
    'https://img.shields.io/github/issues-pr-raw/base/node-reth',
    'https://rustup.rs/',
]
