[package]
name = "tips-core"
version.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
edition.workspace = true

[features]
test-utils = ["dep:alloy-signer-local", "dep:op-alloy-rpc-types"]

[dependencies]
op-alloy-flz.workspace = true
alloy-serde.workspace = true
serde = { workspace = true, features = ["std", "derive"] }
uuid = { workspace = true, features = ["v4", "serde"] }
tracing = { workspace = true, features = ["std"] }
alloy-consensus = { workspace = true, features = ["std"] }
alloy-rpc-types = { workspace = true, features = ["eth"] }
alloy-provider = { workspace = true, features = ["reqwest"] }
alloy-signer-local = { workspace = true, optional = true }
op-alloy-consensus = { workspace = true, features = ["std", "k256", "serde"] }
alloy-primitives = { workspace = true, features = ["map-foldhash", "serde"] }
op-alloy-rpc-types = { workspace = true, features = ["std"], optional = true }
metrics-exporter-prometheus = { workspace = true, features = ["http-listener"] }
tracing-subscriber = { workspace = true, features = ["std", "fmt", "ansi", "env-filter", "json"] }

[dev-dependencies]
alloy-signer-local.workspace = true
serde_json = { workspace = true, features = ["std"] }
op-alloy-rpc-types = { workspace = true, features = ["std"] }
