[package]
name = "base-proposer-bin"
description = "Base Proposer Binary"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[[bin]]
name = "base-proposer"
path = "src/main.rs"

[lints]
workspace = true

[dependencies]
url.workspace = true
eyre.workspace = true
serde.workspace = true
humantime.workspace = true
base-proposer.workspace = true
base-cli-utils.workspace = true
alloy-primitives.workspace = true
clap = { workspace = true, features = ["derive", "env"] }
tokio = { workspace = true, features = ["full"] }
