[package]
name = "kona-proof"
description = "OP Stack Proof SDK"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true

[lints]
workspace = true

[dependencies]
# Workspace
kona-mpt.workspace = true
kona-derive.workspace = true
kona-driver.workspace = true
kona-preimage.workspace = true
kona-executor.workspace = true
base-protocol.workspace = true
kona-registry.workspace = true
kona-genesis = { workspace = true, features = ["serde"] }

# Alloy
alloy-rlp.workspace = true
alloy-eips.workspace = true
alloy-trie.workspace = true
alloy-consensus.workspace = true
alloy-primitives.workspace = true

# Op Alloy
op-alloy-consensus.workspace = true
op-alloy-rpc-types-engine = { workspace = true, features = ["serde"] }

# Execution
op-revm.workspace = true
alloy-op-evm.workspace = true
alloy-evm = { workspace = true, features = ["op"] }

# General
lru.workspace = true
spin.workspace = true
serde.workspace = true
tracing.workspace = true
serde_json.workspace = true
async-trait.workspace = true
thiserror.workspace = true
lazy_static.workspace = true

# KZG
ark-ff.workspace = true
ark-bls12-381.workspace = true

# `std` feature dependencies
tokio = { workspace = true, features = ["full"], optional = true }

[dev-dependencies]
rand.workspace = true
c-kzg.workspace = true
rayon.workspace = true
rstest.workspace = true
tokio = { workspace = true, features = ["full"] }
alloy-eips = { workspace = true, features = ["kzg"] }

[features]
std = [
	"alloy-consensus/std",
	"alloy-eips/std",
	"alloy-evm/std",
	"alloy-op-evm/std",
	"alloy-primitives/std",
	"alloy-rlp/std",
	"alloy-trie/std",
	"ark-bls12-381/std",
	"ark-ff/std",
	"base-protocol/std",
	"dep:tokio",
	"kona-genesis/std",
	"kona-preimage/std",
	"kona-registry/std",
	"op-alloy-consensus/std",
	"op-alloy-rpc-types-engine/std",
	"op-revm/std",
	"serde/std",
	"serde_json/std",
	"spin/std",
	"thiserror/std",
	"tracing/std",
]
