[package]
name = "alloy-op-hardforks"
description = "Bindings for named OP hardforks"

version = "0.4.7"
edition = "2024"
rust-version = "1.88"
authors = ["Alloy Contributors", "OpLabsPBC"]
license.workspace = true
homepage = "https://github.com/ethereum-optimism/optimism"
repository = "https://github.com/ethereum-optimism/optimism"

[lints]
workspace = true

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[dependencies]
alloy-hardforks = { workspace = true }

# ethereum
alloy-chains = { workspace = true }
alloy-primitives = { workspace = true }

# misc
auto_impl = { workspace = true }
serde = { workspace = true, optional = true }

[features]
serde = [
	"dep:serde",
	"alloy-hardforks/serde",
	"alloy-chains/serde",
	"alloy-primitives/serde"
]
