[package]
name = "base-reth-runner"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
description = "Base-specific node launcher wiring"

[lints]
workspace = true

[dependencies]
# internal
base-primitives.workspace = true
base-reth-flashblocks.workspace = true
base-reth-metering.workspace = true
base-txpool.workspace = true

# reth
reth.workspace = true
reth-db.workspace = true
reth-optimism-node.workspace = true
reth-optimism-chainspec.workspace = true

# misc
eyre.workspace = true
futures-util.workspace = true
tracing.workspace = true
derive_more = { workspace = true, features = ["debug"] }
