[package]
name = "tips-maintenance"
version.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
edition.workspace = true

[[bin]]
name = "tips-maintenance"
path = "src/main.rs"

[dependencies]
tips-datastore.workspace = true
tips-audit.workspace = true
op-alloy-consensus.workspace = true
alloy-provider.workspace = true
alloy-primitives.workspace = true
alloy-rpc-types.workspace = true
op-alloy-network.workspace = true
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
anyhow.workspace = true
clap.workspace = true
dotenvy.workspace = true
rdkafka.workspace = true
url.workspace = true
uuid.workspace = true
op-alloy-rpc-types.workspace = true
base-reth-flashblocks-rpc.workspace = true
alloy-rpc-types-mev.workspace = true
sqlx.workspace = true
