[package]
name = "sidecrush"
version = "0.1.0"
edition = "2021"

[dependencies]
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
tokio = { workspace = true }
metrics = { workspace = true }
metrics-derive = { workspace = true }
async-trait = "0.1"
anyhow = "1.0"
clap = { workspace = true }
once_cell = "1"
reth-metrics = { git = "https://github.com/paradigmxyz/reth", tag = "v1.6.0" }

# Ethereum client deps (will be used for header fetching)
alloy-provider = { workspace = true }
alloy-transport-http = { workspace = true }
alloy-rpc-types-eth = { workspace = true }
alloy-consensus = { workspace = true }
alloy-primitives = { workspace = true }

[dev-dependencies]
tokio = { workspace = true, features = ["rt-multi-thread", "macros"] }
tracing = { workspace = true }
