[package]
name = "base-builder"
description = "Base Builder Binary"

version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[lints]
workspace = true

[dependencies]
# Workspace
base-cli-utils.workspace = true
op-rbuilder.workspace = true
metrics.workspace = true

# reth
reth-cli-util.workspace = true
reth-optimism-cli = { workspace = true, optional = true }

[build-dependencies]
vergen = { workspace = true, features = ["build", "cargo", "emit_and_set"] }
vergen-git2.workspace = true

[features]
default = [ "jemalloc" ]
jemalloc = [ "op-rbuilder/jemalloc", "reth-cli-util/jemalloc" ]
telemetry = [ "op-rbuilder/telemetry", "reth-optimism-cli" ]
