[package]
name = "base-builder-bin"
description = "Base Builder Binary"

version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[[bin]]
name = "base-builder"
path = "src/main.rs"

[lints]
workspace = true

[dependencies]
# Workspace
base-builder-cli.workspace = true
base-builder.workspace = true
base-cli-utils.workspace = true

# CLI
clap.workspace = true

# reth
reth-cli-util.workspace = true

[features]
default = [ "jemalloc" ]
jemalloc = [ "base-builder/jemalloc", "reth-cli-util/jemalloc" ]
