[package]
name = "base-builder"
description = "Base Builder Binary"

version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[lints]
workspace = true

[dependencies]
# Workspace
base-builder-cli.workspace = true
base-cli-utils.workspace = true
op-rbuilder.workspace = true

# CLI
dirs-next.workspace = true

# reth
reth-cli-util.workspace = true

[features]
default = [ "jemalloc" ]
jemalloc = [ "op-rbuilder/jemalloc", "reth-cli-util/jemalloc" ]
