[package]
name = "base-consensus-registry"
version.workspace = true
description = "A registry of chain configs"

edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
exclude.workspace = true

[lints]
workspace = true

[dependencies]
# Workspace
base-consensus-genesis = { workspace = true, features = ["serde"] }

# Alloy
alloy-primitives = { workspace = true, features = ["map"] }
alloy-genesis.workspace = true
alloy-eips.workspace = true
alloy-hardforks.workspace = true
alloy-chains.workspace = true
base-alloy-hardforks.workspace = true

# `serde`
toml = { workspace = true, features = ["parse", "serde"] }

# misc
spin.workspace = true

[dev-dependencies]
alloy-eips.workspace = true

[[test]]
name = "hardfork_consistency"
required-features = ["test-utils"]

[features]
default = []
std = [
	"alloy-chains/std",
	"alloy-eips/std",
	"alloy-genesis/std",
	"alloy-primitives/std",
	"base-consensus-genesis/std",
	"toml/std",
]
test-utils = []
