[package]
name = "tips-ingress-writer"
version.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
edition.workspace = true

[[bin]]
name = "tips-ingress-writer"
path = "src/main.rs"

[dependencies]
tips-datastore.workspace = true
tips-audit.workspace=true
alloy-rpc-types-mev.workspace = true
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
anyhow.workspace = true
clap.workspace = true
dotenvy.workspace = true
rdkafka.workspace = true
serde_json.workspace = true
backon.workspace = true
uuid.workspace = true
