[package]
name = "base-txpool-tracing"
description = "Transaction tracing extensions for Base"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[lints]
workspace = true

[dependencies]
# workspace
base-flashblocks.workspace = true
base-node-runner.workspace = true

# reth
reth-node-api.workspace = true
reth-provider.workspace = true
reth-tracing.workspace = true
reth-primitives-traits.workspace = true
reth-transaction-pool.workspace = true

# alloy
alloy-primitives.workspace = true

# async
tokio.workspace = true
tokio-stream.workspace = true
futures.workspace = true

# misc
lru.workspace = true
chrono.workspace = true
metrics.workspace = true
derive_more = { workspace = true, features = ["display"] }
tracing = { workspace = true, features = ["std"] }
metrics-derive.workspace = true

[dev-dependencies]
# workspace
base-flashblocks.workspace = true
base-node-runner = { workspace = true, features = ["test-utils"] }
base-flashblocks-node = { workspace = true, features = ["test-utils"] }

# reth
base-execution-primitives.workspace = true
reth-transaction-pool = { workspace = true, features = ["test-utils"] }

# revm
revm-database.workspace = true

# alloy
alloy-eips = { workspace = true, features = ["std"] }
alloy-consensus = { workspace = true, features = ["std"] }
alloy-rpc-types-engine = { workspace = true, features = ["std"] }

# base-alloy
base-alloy-consensus.workspace = true

# misc
eyre.workspace = true
