[package]
name = "base-alloy-rpc-types-engine"
description = "Base RPC types for the `engine` namespace"

version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
exclude.workspace = true

[lints]
workspace = true

[dependencies]
# Workspace
base-alloy-consensus.workspace = true

# Alloy
alloy-primitives.workspace = true
alloy-eips.workspace = true
alloy-rpc-types-engine.workspace = true
alloy-rlp.workspace = true
alloy-consensus.workspace = true

# Encoding
snap = { workspace = true, optional = true }
ethereum_ssz = { workspace = true, optional = true }
ethereum_ssz_derive = { workspace = true, optional = true }

# serde
serde = { workspace = true, optional = true }
alloy-serde = { workspace = true, optional = true }

# misc
thiserror.workspace = true
arbitrary = { workspace = true, features = ["derive"], optional = true }

# hashing
sha2.workspace = true

derive_more = { workspace = true, features = ["as_ref", "deref_mut"] }

[dev-dependencies]
arbtest.workspace = true
serde_json.workspace = true
arbitrary = { workspace = true, features = ["derive"] }
alloy-primitives = { workspace = true, features = ["arbitrary", "getrandom"] }

[features]
default = [ "serde", "std" ]
std = [
	"alloy-primitives/std",
	"alloy-rpc-types-engine/ssz",
	"alloy-rpc-types-engine/std",
	"base-alloy-consensus/std",
	"dep:ethereum_ssz",
	"dep:ethereum_ssz_derive",
	"dep:snap",
]
serde = [
	"alloy-rpc-types-engine/serde",
	"base-alloy-consensus/serde",
	"dep:alloy-serde",
	"dep:serde",
]
k256 = [ "base-alloy-consensus/k256" ]
arbitrary = [
	"alloy-primitives/arbitrary",
	"alloy-primitives/rand",
	"base-alloy-consensus/arbitrary",
	"dep:arbitrary",
	"std",
]
