[package]
name = "base-engine-ext"
description = "In-process engine client for direct reth communication"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[lints]
workspace = true

[dependencies]
# reth
reth-payload-builder.workspace = true
reth-optimism-node.workspace = true
reth-engine-primitives.workspace = true
reth-payload-primitives.workspace = true

# alloy
alloy-eips.workspace = true
alloy-primitives.workspace = true
alloy-rpc-types-engine.workspace = true

# base-alloy
base-alloy-rpc-types-engine.workspace = true

# misc
tracing.workspace = true
thiserror.workspace = true
