[package]
name = "base-builder-cli"
description = "CLI argument definitions for the Base builder"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[lints]
workspace = true

[dependencies]
# CLI
clap.workspace = true

# reth
reth-optimism-cli = { workspace = true, features = ["otlp"] }
reth-optimism-node.workspace = true
reth-tracing-otlp.workspace = true

# tracing
tracing.workspace = true
tracing-subscriber.workspace = true

# misc
eyre.workspace = true
url.workspace = true
