[package]
name = "base-bundles"
description = "Bundle types for transaction bundles"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[lints]
workspace = true

[features]
test-utils = [ "dep:alloy-signer-local", "dep:op-alloy-rpc-types" ]

[dependencies]
# alloy
alloy-serde.workspace = true
alloy-consensus = { workspace = true, features = ["std"] }
alloy-primitives = { workspace = true, features = ["serde"] }
alloy-provider = { workspace = true, features = ["reqwest"] }

# op-alloy
op-alloy-flz.workspace = true
op-alloy-consensus = { workspace = true, features = ["std", "k256", "serde"] }

# misc
serde = { workspace = true, features = ["std", "derive"] }
uuid = { workspace = true, features = ["v4", "serde"] }

# test-utils (optional)
alloy-signer-local = { workspace = true, optional = true }
op-alloy-rpc-types = { workspace = true, features = ["std"], optional = true }

[dev-dependencies]
# alloy
alloy-signer-local.workspace = true

# op-alloy
op-alloy-rpc-types = { workspace = true, features = ["std"] }

# misc
serde_json = { workspace = true, features = ["std"] }
