[package]
name = "base-cli-utils"
description = "CLI Utilities"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[lints]
workspace = true

[dependencies]
# consensus
base-consensus-registry.workspace = true

# reth
reth-node-core.workspace = true

# alloy
alloy-chains = { workspace = true, features = ["std"] }
alloy-primitives.workspace = true

# cli
clap = { workspace = true, features = ["derive"] }

# tracing
tracing = { workspace = true, features = ["std"] }
tracing-appender.workspace = true
tracing-subscriber = { workspace = true, features = ["fmt", "env-filter", "json", "tracing-log"] }

# metrics
metrics.workspace = true
metrics-process = { workspace = true, features = ["metrics-rs"] }
metrics-exporter-prometheus = { workspace = true, features = ["http-listener"] }

# misc
eyre.workspace = true
dirs-next.workspace = true
serde = { workspace = true, features = ["derive", "std"] }
tokio = { workspace = true, features = ["full"] }

[dev-dependencies]
rstest.workspace = true
serde_json = { workspace = true, features = ["std"] }

[target.'cfg(unix)'.dependencies]
libc.workspace = true
