[package]
name = "tips-audit"
version.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
edition.workspace = true

[[bin]]
name = "tips-audit"
path = "src/bin/main.rs"

[dependencies]
tips-core = { workspace = true, features = ["test-utils"] }
tokio = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
anyhow = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
uuid = { workspace = true }
async-trait = { workspace = true }
alloy-primitives = { workspace = true }
alloy-consensus = { workspace = true }
alloy-provider = { workspace = true }
op-alloy-consensus = { workspace = true }
clap = { workspace = true }
dotenvy = { workspace = true }
rdkafka = { workspace = true }
aws-config = { workspace = true }
aws-sdk-s3 = { workspace = true }
aws-credential-types = { workspace = true }
bytes = { workspace = true }
metrics = { workspace = true }
metrics-derive = { workspace = true }

[dev-dependencies]
testcontainers = { workspace = true }
testcontainers-modules = { workspace = true }