[package]
name = "base-execution-consensus"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
exclude = [".github/"]

[lints]
workspace = true

[dependencies]
# reth
reth-execution-types.workspace = true
reth-chainspec.workspace = true
reth-consensus-common.workspace = true
reth-consensus.workspace = true
reth-primitives-traits.workspace = true
reth-storage-api.workspace = true
reth-storage-errors.workspace = true
reth-trie-common.workspace = true

# op-reth
base-execution-forks.workspace = true
base-execution-primitives.workspace = true

# ethereum
alloy-eips.workspace = true
alloy-primitives.workspace = true
alloy-consensus.workspace = true
alloy-trie.workspace = true
revm.workspace = true

# misc
tracing.workspace = true
thiserror.workspace = true
base-execution-chainspec.workspace = true

[dev-dependencies]
reth-provider = { workspace = true, features = ["test-utils"] }
reth-db-common.workspace = true
reth-revm.workspace = true
reth-trie.workspace = true
base-execution-node.workspace = true

alloy-chains.workspace = true

base-alloy-consensus.workspace = true

[features]
default = [ "std" ]
std = [
	"alloy-chains/std",
	"alloy-consensus/std",
	"alloy-eips/std",
	"alloy-primitives/std",
	"alloy-trie/std",
	"base-alloy-consensus/std",
	"base-execution-chainspec/std",
	"base-execution-forks/std",
	"base-execution-primitives/std",
	"reth-chainspec/std",
	"reth-consensus-common/std",
	"reth-consensus/std",
	"reth-execution-types/std",
	"reth-primitives-traits/std",
	"reth-revm/std",
	"reth-storage-api/std",
	"reth-storage-errors/std",
	"reth-trie-common/std",
	"revm/std",
	"thiserror/std",
	"tracing/std",
]
