[package]
name = "op-enclave-core"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
alloy-chains.workspace = true
alloy-eips.workspace = true
alloy-primitives.workspace = true
alloy-consensus.workspace = true
alloy-rlp.workspace = true
alloy-trie.workspace = true
kona-genesis.workspace = true
op-alloy-consensus.workspace = true
kona-protocol.workspace = true
serde.workspace = true
serde_json.workspace = true
hex.workspace = true
thiserror.workspace = true

[lints]
workspace = true
