[package]
name = "mempool-rebroadcaster"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
path = "src/lib.rs"

[lints]
workspace = true

[dependencies]
serde = { workspace = true, features = ["std"] }
serde_json = { workspace = true, features = ["std"] }
tracing = { workspace = true, features = ["std"] }
tokio = { workspace = true }

# alloy
alloy-primitives.workspace = true
alloy-eips = { workspace = true, features = ["std"] }
alloy-rpc-types = { workspace = true, features = ["txpool"] }
alloy-rpc-types-eth = { workspace = true, features = ["std"] }
alloy-consensus = { workspace = true, features = ["std"] }
alloy-trie.workspace = true
alloy-provider = { workspace = true, features = ["txpool-api"] }
