[package]
name = "mempool-rebroadcaster"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "mempool-rebroadcaster"
path = "src/main.rs"

[dependencies]
clap = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
tokio = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
dotenvy = "0.15.7"

# alloy
alloy-primitives.workspace = true
alloy-eips.workspace = true
alloy-rpc-types = { workspace = true, features = ["txpool"] }
alloy-rpc-types-eth.workspace = true
alloy-consensus.workspace = true
alloy-trie.workspace = true
alloy-provider = { workspace = true, features = ["txpool-api"] }

