[package]
name = "mempool-rebroadcaster"
version.workspace = true
edition.workspace = true
license.workspace = true

[lints]
workspace = true

[[bin]]
name = "mempool-rebroadcaster"
path = "src/main.rs"

[dependencies]
clap = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
tokio = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
dotenvy = { workspace = true }

# alloy
alloy-primitives.workspace = true
alloy-eips.workspace = true
alloy-rpc-types = { workspace = true, features = ["txpool"] }
alloy-rpc-types-eth.workspace = true
alloy-consensus.workspace = true
alloy-trie.workspace = true
alloy-provider = { workspace = true, features = ["txpool-api"] }

