[package]
name = "op-enclave-client"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
op-enclave-core.workspace = true

# Alloy types
alloy-primitives.workspace = true
alloy-consensus.workspace = true

# RPC
jsonrpsee.workspace = true
async-trait.workspace = true

# Serialization
serde.workspace = true
serde_json.workspace = true

# Error handling
thiserror.workspace = true

[lints]
workspace = true
