[package]
name = "mempool-rebroadcaster-bin"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "mempool-rebroadcaster"
path = "src/main.rs"

[lints]
workspace = true

[dependencies]
clap = { workspace = true }
dotenvy.workspace = true
mempool-rebroadcaster = { workspace = true }
tracing = { workspace = true, features = ["std"] }
tracing-subscriber = { workspace = true }
tokio = { workspace = true }
