[package]
name = "mempool-rebroadcaster-bin"
version.workspace = true
edition.workspace = true

[[bin]]
name = "mempool-rebroadcaster"
path = "src/main.rs"

[dependencies]
clap = { workspace = true }
dotenvy = "0.15.7"
mempool-rebroadcaster = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
tokio = { workspace = true }
