[package]
name = "base-execution-forks"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
description = "Optimism hardforks used in op-reth"

[lints]
workspace = true

[dependencies]
# reth
reth-ethereum-forks.workspace = true

# base
base-alloy-hardforks.workspace = true

# ethereum
alloy-primitives.workspace = true

# misc
spin.workspace = true

[features]
default = [ "std" ]
std = [ "alloy-primitives/std", "reth-ethereum-forks/std", "spin/std" ]
serde = [
	"alloy-primitives/serde",
	"base-alloy-hardforks/serde",
	"reth-ethereum-forks/serde",
]
