[package]
name = "rbuilder-bundle-pool-operations"
version = "0.1.0"
edition = "2021"

[dependencies]
transaction-pool-bundle-ext = { path = "../.." }
rbuilder = { path = "../../../rbuilder" }

alloy-primitives.workspace = true
alloy-rpc-types-beacon.workspace = true
reth-primitives = { workspace = true }
reth-provider = {workspace = true}
derive_more = { workspace = true }
eyre = { workspace = true }
tokio = { workspace = true }
tokio-util = { workspace = true }
tracing = { workspace = true }

[features]
optimism = [
	"rbuilder/optimism",
	"reth-primitives/optimism",
]
