[package]
name = "audit-archiver"
version.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
edition.workspace = true

[[bin]]
name = "audit-archiver"
path = "src/main.rs"

[lints]
workspace = true

[dependencies]
base-cli-utils.workspace = true
audit-archiver-lib.workspace = true
clap.workspace = true
serde.workspace = true
tokio.workspace = true
anyhow.workspace = true
tracing = { workspace = true, features = ["std"] }
dotenvy.workspace = true
rdkafka.workspace = true
aws-config.workspace = true
aws-sdk-s3.workspace = true
aws-credential-types.workspace = true
