[package]
name = "base-txpool-rpc"
description = "Transaction pool RPC APIs for Base"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[lints]
workspace = true

[dependencies]
# workspace
base-node.workspace = true

# reth
reth-transaction-pool.workspace = true

# alloy
alloy-primitives.workspace = true

# rpc
jsonrpsee.workspace = true

# misc
serde.workspace = true
tracing.workspace = true

[dev-dependencies]
eyre.workspace = true
httpmock.workspace = true
serde_json.workspace = true
tokio.workspace = true
reth-transaction-pool = { workspace = true, features = ["test-utils"] }
