[package]
name = "base-builder-metering"
description = "Resource metering backend for the OP Stack block builder"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[lints]
workspace = true

[dependencies]
base-builder-core.workspace = true
base-bundles.workspace = true
base-client-node.workspace = true
alloy-primitives.workspace = true
dashmap.workspace = true
concurrent-queue.workspace = true
jsonrpsee.workspace = true
tracing.workspace = true

[dev-dependencies]
alloy-primitives.workspace = true
