name = "Sepolia Dev 0"
protocol_versions_addr = "0x252CbE9517F731C618961D890D534183822dcC8d"
superchain_config_addr = "0x02d91Cf852423640d93920BE0CAdceC0E7A00FA7"

[hardforks]
canyon_time = 0
delta_time = 0
ecotone_time = 1706634000 # Tue 30 Jan 2024 17:00:00 UTC
fjord_time = 1715961600   # Fri May 17 2024 16:00:00 UTC
granite_time = 1723046400 # Wed Aug 7 16:00:00 UTC 2024
holocene_time = 1731682800 # Fri Nov 15 15:00:00 UTC 2024
pectra_blob_schedule_time = 1741687200 # Tue Mar 11 10:00:00 UTC 2025
isthmus_time = 1744300800 # Thu Apr 10 16:00:00 UTC 2025
jovian_time = 1762185600 # Mon 3 Nov 2025 16:00:00 UTC

[l1]
  chain_id = 11155111
  public_rpc = "https://ethereum-sepolia-rpc.publicnode.com"
  explorer = "https://eth-sepolia.blockscout.com"
