[package]
name = "base-test-utils"
description = "Shared test utilities: accounts, genesis config, and contract bindings"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[lints]
workspace = true

[dependencies]
# alloy
alloy-eips.workspace = true
alloy-signer.workspace = true
alloy-genesis = { workspace = true, features = ["std"] }
alloy-contract.workspace = true
alloy-sol-types = { workspace = true, features = ["std"] }
alloy-consensus = { workspace = true, features = ["std"] }
alloy-primitives = { workspace = true, features = ["serde"] }
alloy-signer-local.workspace = true
alloy-sol-macro = { workspace = true, features = ["json"] }

# base-alloy
base-alloy-network.workspace = true
base-alloy-rpc-types.workspace = true

# misc
eyre.workspace = true
serde_json = { workspace = true, features = ["std"] }
