[package]
name = "base-node-core"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[lints]
workspace = true

[dependencies]
# reth
reth-chainspec.workspace = true
## ensure secp256k1 recovery with rayon support is activated
reth-primitives-traits = { workspace = true, features = ["secp256k1", "rayon"] }
reth-payload-builder.workspace = true
reth-consensus.workspace = true
reth-node-api.workspace = true
reth-node-builder.workspace = true
reth-tracing.workspace = true
reth-provider.workspace = true
reth-transaction-pool.workspace = true
reth-network.workspace = true
reth-evm.workspace = true
reth-rpc-server-types.workspace = true
reth-tasks.workspace = true
reth-trie-common.workspace = true
reth-node-core.workspace = true
reth-rpc-engine-api.workspace = true
reth-rpc-api.workspace = true
reth-db.workspace = true
reth-db-api.workspace = true

# op-reth
base-execution-payload-builder.workspace = true
base-execution-evm = { workspace = true, features = ["std", "rpc"] }
base-execution-rpc.workspace = true
base-execution-storage.workspace = true
base-execution-txpool.workspace = true
base-execution-chainspec.workspace = true
base-execution-consensus = { workspace = true, features = ["std"] }
base-execution-forks.workspace = true
base-execution-primitives = { workspace = true, features = [
  "serde",
  "serde-bincode-compat",
  "reth-codec",
] }
base-execution-exex = { workspace = true, features = ["metrics"] }
base-execution-trie = { workspace = true, features = ["metrics"] }

# revm with required optimism features
# Note: this must be kept to ensure all features are properly enabled/forwarded
revm = { workspace = true, features = [
  "secp256k1",
  "blst",
  "c-kzg",
  "memory_limit",
] }
base-revm.workspace = true

# ethereum
alloy-primitives.workspace = true
base-alloy-consensus.workspace = true
base-alloy-rpc-types-engine = { workspace = true, features = ["reth"] }
alloy-rpc-types-engine.workspace = true
alloy-rpc-types-eth.workspace = true
alloy-consensus.workspace = true

# async
tokio.workspace = true

# misc
clap.workspace = true
serde.workspace = true
eyre.workspace = true
humantime.workspace = true
futures.workspace = true
tracing.workspace = true

# test-utils dependencies
reth-e2e-test-utils = { workspace = true, optional = true }
alloy-genesis = { workspace = true, optional = true }
serde_json = { workspace = true, optional = true }

[dev-dependencies]
base-node-core = { workspace = true, features = ["test-utils"] }
reth-db = { workspace = true, features = ["test-utils"] }
reth-node-builder = { workspace = true, features = ["test-utils"] }
reth-provider = { workspace = true, features = ["test-utils"] }
reth-tasks.workspace = true
reth-payload-util.workspace = true
reth-revm = { workspace = true, features = ["std"] }
reth-rpc.workspace = true
reth-rpc-eth-types.workspace = true
reth-stages-types.workspace = true
reth-trie-db.workspace = true

alloy-network.workspace = true
base-alloy-hardforks.workspace = true
base-alloy-network.workspace = true
futures.workspace = true

[features]
default = [ "reth-codec" ]
asm-keccak = [
	"alloy-primitives/asm-keccak",
	"base-node-core/asm-keccak",
	"reth-node-core/asm-keccak",
	"revm/asm-keccak",
]
keccak-cache-global = [
	"alloy-primitives/keccak-cache-global",
	"base-node-core/keccak-cache-global",
	"reth-node-core/keccak-cache-global",
]
js-tracer = [
	"base-node-core/js-tracer",
	"reth-node-builder/js-tracer",
	"reth-rpc-eth-types/js-tracer",
	"reth-rpc/js-tracer",
]
test-utils = [
	"alloy-genesis",
	"base-execution-exex/test-utils",
	"base-execution-primitives/arbitrary",
	"base-node-core/test-utils",
	"reth-chainspec/test-utils",
	"reth-codec",
	"reth-consensus/test-utils",
	"reth-db-api/test-utils",
	"reth-db/test-utils",
	"reth-e2e-test-utils",
	"reth-evm/test-utils",
	"reth-network/test-utils",
	"reth-node-builder/test-utils",
	"reth-payload-builder/test-utils",
	"reth-primitives-traits/test-utils",
	"reth-provider/test-utils",
	"reth-revm/test-utils",
	"reth-stages-types/test-utils",
	"reth-tasks/test-utils",
	"reth-transaction-pool/test-utils",
	"reth-trie-common/test-utils",
	"reth-trie-db/test-utils",
	"serde_json",
]
reth-codec = [ "base-execution-primitives/reth-codec" ]

[[test]]
name = "e2e_testsuite"
path = "tests/e2e-testsuite/main.rs"
