[package]
name = "base-reth-node"
description = "Base Reth Binary"

version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[lints]
workspace = true

[dependencies]
# internal
base-cli-utils.workspace = true
base-client-node.workspace = true
base-flashblocks-node.workspace = true
base-metering.workspace = true
base-txpool.workspace = true

# reth
reth-optimism-node.workspace = true
reth-optimism-cli.workspace = true
reth-cli-util.workspace = true

# misc
clap.workspace = true

[features]
default = []
jemalloc = [ "reth-cli-util/jemalloc", "reth-optimism-cli/jemalloc" ]

[dev-dependencies]
base-client-node = { workspace = true, features = ["test-utils"] }
base-metering.workspace = true
base-txpool.workspace = true
tokio = { workspace = true, features = ["rt-multi-thread", "macros"] }
eyre.workspace = true
jsonrpsee = { workspace = true, features = ["http-client"] }
jsonrpsee-types.workspace = true
serde_json.workspace = true
alloy-primitives.workspace = true
