[package]
name = "base-reth-node"
description = "Base Reth Binary"

version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[lints]
workspace = true

[dependencies]
# internal
base-cli-utils.workspace = true
base-client-node.workspace = true
base-flashblocks.workspace = true
base-metering.workspace = true
base-txpool.workspace = true

# reth
reth-optimism-node.workspace = true
reth-optimism-cli = { path = "../../crates/optimism/cli" }
reth-cli-util.workspace = true
reth-optimism-exex.workspace = true

# misc
clap.workspace = true

[features]
default = []
jemalloc = [ "reth-cli-util/jemalloc", "reth-optimism-cli/jemalloc" ]
