[package]
name = "base-reth-node"
description = "Base Reth Binary"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[lints]
workspace = true

[dependencies]
# workspace
base-txpool.workspace = true
base-metering.workspace = true
base-cli-utils.workspace = true
base-flashblocks.workspace = true
base-client-node.workspace = true
base-flashblocks-node.workspace = true
base-proofs-extension.workspace = true

# reth
reth-cli-util.workspace = true
reth-optimism-node.workspace = true
reth-optimism-cli = { workspace = true, features = ["otlp"] }

# cli
clap.workspace = true

[features]
default = [ "jemalloc" ]
jemalloc = [ "reth-cli-util/jemalloc", "reth-optimism-cli/jemalloc" ]
