[package]
name = "basectl"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "basectl"
path = "main.rs"

[lints]
workspace = true

[dependencies]
anyhow = { workspace = true }
basectl-cli = { workspace = true }
clap = { workspace = true, features = ["derive"] }
rustls = { workspace = true, features = ["ring"] }
tokio = { workspace = true, features = ["rt-multi-thread", "macros"] }
