[package]
name = "websocket-proxy"
description = "WebSocket Proxy"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[lib]
name = "websocket_proxy"

[lints]
workspace = true

[dependencies]
http.workspace = true
anyhow.workspace = true
brotli = { workspace = true, features = ["std"] }
metrics.workspace = true
futures.workspace = true
backoff.workspace = true
base-cli-utils.workspace = true
thiserror = { workspace = true, features = ["std"] }
tracing = { workspace = true, features = ["std"] }
tokio-util.workspace = true
serde_json = { workspace = true, features = ["std"] }
metrics-derive.workspace = true
tokio-tungstenite.workspace = true
serde = { workspace = true, features = ["derive", "std"] }
tokio = { workspace = true, features = ["full"] }
axum = { workspace = true, features = ["ws", "query", "tokio", "http1"] }
metrics-exporter-prometheus = { workspace = true, features = ["http-listener"] }

[dev-dependencies]
reqwest.workspace = true
