[package]
name = "websocket-proxy"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license = "MIT"

[lib]
name = "websocket_proxy"

[lints]
workspace = true

[dependencies]
http.workspace = true
brotli.workspace = true
metrics.workspace = true
futures.workspace = true
backoff.workspace = true
thiserror.workspace = true
tracing.workspace = true
tokio-util.workspace = true
serde_json.workspace = true
metrics-derive.workspace = true
tokio-tungstenite.workspace = true
serde = { workspace = true, features = ["derive"] }
tokio = { workspace = true, features = ["full"] }
axum = { workspace = true, features = ["ws", "query", "tokio", "http1"] }

[dev-dependencies]
reqwest.workspace = true
tokio-tungstenite.workspace = true
