[package]
name = "reth-optimism-txpool"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
description = "OP-Reth Transaction Pool"

[lints]
workspace = true

[dependencies]
# ethereum
alloy-consensus.workspace = true
alloy-eips.workspace = true
alloy-primitives.workspace = true

# reth
reth-chainspec.workspace = true
reth-evm.workspace = true
reth-primitives-traits.workspace = true
reth-storage-api.workspace = true
reth-transaction-pool.workspace = true

# revm
base-revm.workspace = true

# optimism
base-alloy-flz.workspace = true
base-alloy-consensus.workspace = true
reth-optimism-evm.workspace = true
reth-optimism-forks.workspace = true
reth-optimism-primitives.workspace = true

# misc
c-kzg.workspace = true
derive_more.workspace = true
parking_lot.workspace = true

[dev-dependencies]
tokio = { workspace = true, features = ["time"] }
reth-optimism-chainspec.workspace = true
reth-provider = { workspace = true, features = ["test-utils"] }
