[package]
name = "base-metering"
description = "Metering RPC for Base node"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[lints]
workspace = true

[dependencies]
# workspace
base-bundles.workspace = true
base-flashblocks.workspace = true
base-client-node.workspace = true

# reth
reth-evm.workspace = true
reth-revm.workspace = true
reth-provider.workspace = true
reth-trie-common.workspace = true
reth-optimism-evm.workspace = true
reth-primitives-traits.workspace = true
reth-optimism-chainspec.workspace = true
reth-optimism-primitives.workspace = true

# revm
revm-database.workspace = true

# op-revm
op-revm.workspace = true

# alloy
alloy-eips = { workspace = true, features = ["std"] }
alloy-consensus = { workspace = true, features = ["std"] }
alloy-primitives.workspace = true
alloy-rpc-types-engine.workspace = true

# rpc
jsonrpsee.workspace = true

# metrics
metrics.workspace = true
metrics-derive.workspace = true

# misc
eyre.workspace = true
serde = { workspace = true, features = ["std"] }
tracing = { workspace = true, features = ["std"] }
arc-swap.workspace = true
derive_more.workspace = true

[dev-dependencies]
# workspace
base-flashblocks.workspace = true
base-primitives.workspace = true
base-client-node = { workspace = true, features = ["test-utils"] }

# reth
reth-db-common.workspace = true
reth-optimism-node.workspace = true
reth-db = { workspace = true, features = ["op", "test-utils"] }
reth-transaction-pool = { workspace = true, features = ["test-utils"] }

# revm
revm-bytecode.workspace = true
revm-context-interface.workspace = true

# alloy
alloy-genesis = { workspace = true, features = ["std"] }
alloy-rpc-client.workspace = true

# op-alloy
op-alloy-network.workspace = true
op-alloy-consensus.workspace = true

# misc
url.workspace = true
rand.workspace = true
tokio.workspace = true
