[package]
name = "base-metering"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
description = "Metering RPC for Base node"

[lints]
workspace = true

[dependencies]
# workspace
base-bundles.workspace = true
base-client-node.workspace = true
base-flashblocks.workspace = true

# reth
reth-provider.workspace = true
reth-primitives-traits.workspace = true
reth-evm.workspace = true
reth-optimism-evm.workspace = true
reth-optimism-chainspec.workspace = true
reth-optimism-primitives.workspace = true
reth-revm.workspace = true
reth-trie-common.workspace = true

# revm
revm-database.workspace = true

# op
op-revm.workspace = true
op-alloy-consensus.workspace = true

# alloy
alloy-primitives.workspace = true
alloy-consensus.workspace = true
alloy-eips.workspace = true

# rpc
jsonrpsee.workspace = true

# misc
arc-swap.workspace = true
metrics.workspace = true
metrics-derive.workspace = true
tracing.workspace = true
eyre.workspace = true
serde.workspace = true
derive_more.workspace = true

[dev-dependencies]
base-client-node = { workspace = true, features = ["test-utils"] }
reth-db = { workspace = true, features = ["op", "test-utils"] }
reth-db-common.workspace = true
reth-optimism-node.workspace = true
reth-transaction-pool = { workspace = true, features = ["test-utils"] }
alloy-genesis.workspace = true
alloy-rpc-client.workspace = true
op-alloy-consensus.workspace = true
rand.workspace = true
tokio.workspace = true
op-alloy-network.workspace = true
revm-context-interface.workspace = true
