[package]
name = "base-cli-utils"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
description = "CLI Utilities"

[lints]
workspace = true

[dependencies]
reth.workspace = true
tokio = { workspace = true, features = ["full"] }
eyre.workspace = true
clap = { workspace = true, features = ["derive"] }
tracing.workspace = true
