[package]
name = "base-cli-utils"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
description = "CLI Utilities"

[lints]
workspace = true

[dependencies]
reth.workspace = true
