[package]
name = "base-cli-utils"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
description = "CLI Utilities"

[lints]
workspace = true

[dependencies]
eyre.workspace = true
tracing.workspace = true
reth-node-core.workspace = true

tokio = { workspace = true, features = ["full"] }
clap = { workspace = true, features = ["derive"] }

# Metrics
metrics-process.workspace = true
metrics-exporter-prometheus = { workspace = true, features = ["http-listener"] }

[target.'cfg(unix)'.dependencies]
libc = "0.2"
