[package]
name = "base-consensus"
description = "Base Consensus Binary"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[[bin]]
name = "base-consensus"
path = "src/main.rs"

[lints]
workspace = true

[dependencies]
# workspace
base-consensus-cli.workspace = true
base-cli-utils.workspace = true
base-client-cli.workspace = true

# alloy
alloy-chains.workspace = true
alloy-primitives.workspace = true

# consensus
base-consensus-genesis.workspace = true
base-consensus-registry.workspace = true
base-consensus-derive = { workspace = true, features = ["metrics"] }
base-consensus-disc = { workspace = true, features = ["metrics"] }
base-consensus-gossip = { workspace = true, features = ["metrics"] }
base-consensus-engine = { workspace = true, features = ["metrics"] }
base-consensus-node = { workspace = true, features = ["metrics"] }
base-consensus-providers = { workspace = true, features = ["metrics"] }

# cli
strum.workspace = true
clap.workspace = true

# tracing
tracing = { workspace = true, features = ["std"] }

# metrics
metrics.workspace = true

# misc
eyre.workspace = true
serde.workspace = true
