[package]
name = "base-consensus"
description = "Base Consensus Binary"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[[bin]]
name = "base-consensus"
path = "src/main.rs"

[lints]
workspace = true

[dependencies]
# workspace
base-cli-utils.workspace = true
base-client-cli.workspace = true

# kona
kona-genesis.workspace = true
kona-derive = { workspace = true, features = ["metrics"] }
kona-disc = { workspace = true, features = ["metrics"] }
kona-gossip = { workspace = true, features = ["metrics"] }
kona-engine = { workspace = true, features = ["metrics"] }
kona-node-service = { workspace = true, features = ["metrics"] }
kona-providers-alloy = { workspace = true, features = ["metrics"] }

# cli
strum.workspace = true
clap.workspace = true

# tracing
tracing = { workspace = true, features = ["std"] }

# metrics
metrics.workspace = true

# misc
eyre.workspace = true
