[package]
name = "base-consensus"
description = "Base Consensus Binary"

version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[lints]
workspace = true

[dependencies]
# Workspace
base-cli-utils.workspace = true
base-client-cli.workspace = true

# Kona
kona-disc = { workspace = true, features = ["metrics"] }
kona-derive = { workspace = true, features = ["metrics"] }
kona-engine = { workspace = true, features = ["metrics"] }
kona-genesis.workspace = true
kona-gossip = { workspace = true, features = ["metrics"] }
kona-node-service = { workspace = true, features = ["metrics"] }
kona-providers-alloy = { workspace = true, features = ["metrics"] }
rollup-boost-kona.workspace = true

# Alloy
alloy-rpc-types-engine.workspace = true

# Misc
url.workspace = true

# Reth (feature unification)
reth-optimism-primitives.workspace = true

# CLI
clap.workspace = true
eyre.workspace = true
strum.workspace = true

# Tracing
tracing.workspace = true

# Metrics
metrics.workspace = true

[build-dependencies]
vergen = { workspace = true, features = ["build", "cargo", "emit_and_set"] }
vergen-git2.workspace = true
