[package]
name = "base-consensus-providers"
version.workspace = true
description = "Alloy Backed Providers"

edition.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[dependencies]
# consensus
base-macros.workspace = true
base-consensus-genesis.workspace = true
base-protocol.workspace = true
base-consensus-derive.workspace = true

# Alloy
alloy-serde = { workspace = true, features = ["std"] }
alloy-eips = { workspace = true, features = ["kzg", "std"] }
alloy-transport.workspace = true
alloy-transport-http = { workspace = true, features = ["reqwest", "reqwest-rustls-tls", "hyper", "hyper-tls", "jwt-auth"] }
alloy-consensus = { workspace = true, features = ["std"] }
alloy-rpc-types-beacon.workspace = true
alloy-rpc-types-engine = { workspace = true, features = ["std"] }
alloy-rpc-client.workspace = true
alloy-provider = { workspace = true, features = ["ipc", "ws", "reqwest"] }
alloy-primitives = { workspace = true, features = ["map"] }

# Base Alloy
base-alloy-consensus.workspace = true
base-alloy-network.workspace = true

# Misc
lru.workspace = true
serde = { workspace = true, features = ["std"] }
thiserror = { workspace = true, features = ["std"] }
async-trait.workspace = true
tower.workspace = true
url.workspace = true
http-body-util.workspace = true

c-kzg.workspace = true

# `metrics` feature
metrics = { workspace = true, optional = true }

[features]
default = []
metrics = [ "base-consensus-derive/metrics", "dep:metrics" ]

[dev-dependencies]
tokio.workspace = true
httpmock.workspace = true
serde_json = { workspace = true, features = ["std"] }
