[package]
name = "base-execution-exex"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
description = "Execution extensions for OP-Reth"

[lints]
workspace = true

[dependencies]
# reth
reth-exex.workspace = true
reth-execution-types.workspace = true
reth-node-api.workspace = true
reth-trie.workspace = true
reth-provider.workspace = true

# op-reth
# proofs exex handles `TrieUpdates` in notifications
base-execution-trie = { workspace = true, features = ["serde-bincode-compat"] }

# alloy
alloy-consensus.workspace = true
alloy-eips.workspace = true

# misc
eyre.workspace = true
futures.workspace = true
tracing.workspace = true
tokio.workspace = true

[dev-dependencies]
reth-db = { workspace = true, features = ["test-utils"] }
reth-node-builder.workspace = true
base-node-core.workspace = true
base-execution-chainspec.workspace = true
reth-primitives-traits.workspace = true
reth-ethereum-primitives.workspace = true
reth-exex-test-utils.workspace = true
tempfile.workspace = true

[features]
test-utils = [
	"base-node-core/test-utils",
	"reth-db/test-utils",
	"reth-ethereum-primitives/test-utils",
	"reth-node-builder/test-utils",
	"reth-primitives-traits/test-utils",
	"reth-provider/test-utils",
	"reth-trie/test-utils",
]
metrics = [ "base-execution-trie/metrics", "reth-trie/metrics" ]

[package.metadata.cargo-udeps.ignore]
development = [
    "reth-node-builder",
    "base-node-core",
    "base-execution-chainspec",
    "tempfile.workspace",
]
