[package]
name = "reth-optimism-exex"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
description = "Execution extensions for OP-Reth"

[lints]
workspace = true

[dependencies]
# reth
reth-exex.workspace = true
reth-execution-types.workspace = true
reth-node-types.workspace = true
reth-node-api.workspace = true
reth-trie.workspace = true
reth-provider.workspace = true

# op-reth
# proofs exex handles `TrieUpdates` in notifications
reth-optimism-trie = { workspace = true, features = ["serde-bincode-compat"] }

# alloy
alloy-consensus.workspace = true
alloy-eips.workspace = true

# misc
eyre.workspace = true
futures-util.workspace = true
tracing.workspace = true
tokio.workspace = true

[dev-dependencies]
futures.workspace = true
reth-db = { workspace = true, features = ["op", "test-utils"] }
reth-node-builder.workspace = true
reth-optimism-node.workspace = true
reth-optimism-chainspec.workspace = true
reth-primitives-traits.workspace = true
reth-ethereum-primitives.workspace = true
reth-exex-test-utils.workspace = true
tempfile.workspace = true

[features]
test-utils = [
    "reth-db/test-utils",
    "reth-trie/test-utils",
    "reth-node-builder/test-utils",
    "reth-optimism-node/test-utils",
    "reth-provider/test-utils",
    "reth-ethereum-primitives/test-utils",
    "reth-primitives-traits/test-utils",
]
metrics = ["reth-optimism-trie/metrics"]

[package.metadata.cargo-udeps.ignore]
development = [
    "reth-node-builder",
    "reth-optimism-node",
    "reth-optimism-chainspec",
    "tempfile.workspace",
]
