[package]
name = "account-abstraction-core"
version.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
edition.workspace = true

[dependencies]
tips-core.workspace = true
alloy-serde.workspace = true
async-trait.workspace = true
alloy-sol-types.workspace = true
op-alloy-network.workspace = true
serde = { workspace = true, features = ["std", "derive"] }
tokio = { workspace = true, features = ["full"] }
tracing = { workspace = true, features = ["std"] }
anyhow = { workspace = true, features = ["std"] }
serde_json = { workspace = true, features = ["std"] }
rdkafka = { workspace = true, features = ["tokio", "libz"] }
alloy-rpc-types = { workspace = true, features = ["eth"] }
jsonrpsee = { workspace = true, features = ["server", "macros"] }
alloy-provider = { workspace = true, features = ["reqwest"] }
alloy-primitives = { workspace = true, features = ["map-foldhash", "serde"] }

[dev-dependencies]
wiremock.workspace = true
alloy-primitives = { workspace = true, features = ["map-foldhash", "serde"] }
