[package]
name = "base-roxy"
description = "Extensible and Modular RPC request router and proxy"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[lints]
workspace = true

[dependencies]

# alloy
alloy-json-rpc.workspace = true

# networking
reqwest = { workspace = true, features = ["json"] }

# async
tokio.workspace = true
async-trait.workspace = true

# general
derive_more = { workspace = true, features = ["debug", "display", "error"] }

[dev-dependencies]
rstest.workspace = true
