name = "Sepolia"
protocol_versions_addr = "0x79ADD5713B383DAa0a138d3C4780C7A1804a8090"
superchain_config_addr = "0xC2Be75506d5724086DEB7245bd260Cc9753911Be"

[hardforks]
canyon_time =  1699981200 # Tue 14 Nov 2023 17:00:00 UTC
delta_time =   1703203200 # Fri 22 Dec 2023 00:00:00 UTC
ecotone_time = 1708534800 # Wed 21 Feb 2024 17:00:00 UTC
fjord_time =   1716998400 # Wed 29 May 2024 16:00:00 UTC
granite_time = 1723478400 # Mon Aug 12 16:00:00 UTC 2024
holocene_time = 1732633200 # Tue Nov 26 15:00:00 UTC 2024
pectra_blob_schedule_time = 1742486400 # Thu Mar 20 16:00:00 UTC 2025
isthmus_time = 1744905600 # Thu Apr 17 16:00:00 UTC 2025
jovian_time = 1763568001 # Wed 19 Nov 2025 16:00:01 UTC

[l1]
  chain_id = 11155111
  public_rpc = "https://ethereum-sepolia-rpc.publicnode.com"
  explorer = "https://eth-sepolia.blockscout.com"
