[package]
name = "base-client-node"
description = "Primitive types and traits for Base node runner extensions"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[lints]
workspace = true

[features]
test-utils = [
	"dep:base-test-utils",
	"dep:alloy-eips",
	"dep:alloy-genesis",
	"dep:alloy-primitives",
	"dep:alloy-provider",
	"dep:alloy-rpc-client",
	"dep:alloy-rpc-types",
	"dep:alloy-rpc-types-engine",
	"dep:alloy-signer",
	"dep:base-alloy-network",
	"dep:base-alloy-rpc-types-engine",
	"dep:chrono",
	"dep:jsonrpsee",
	"dep:reth-chainspec",
	"dep:reth-ipc",
	"dep:reth-node-core",
	"dep:reth-primitives-traits",
	"dep:reth-rpc-layer",
	"dep:reth-tasks",
	"dep:tower",
	"dep:tracing-subscriber",
	"dep:url",
	"reth-chainspec/test-utils",
	"reth-db/test-utils",
	"reth-evm/test-utils",
	"reth-node-builder/test-utils",
	"reth-optimism-node/test-utils",
	"reth-primitives-traits?/test-utils",
	"reth-provider/test-utils",
	"reth-tasks?/test-utils",
	"reth-transaction-pool/test-utils",
]

[dependencies]
# workspace
base-cli-utils.workspace = true
base-test-utils = { workspace = true, optional = true }

# reth
reth-evm.workspace = true
reth-exex.workspace = true
reth-tracing.workspace = true
reth-provider.workspace = true
reth-rpc-api.workspace = true
reth-node-api.workspace = true
reth-node-builder.workspace = true
reth-optimism-rpc = { workspace = true, features = ["client"] }
reth-optimism-forks.workspace = true
reth-optimism-node.workspace = true
reth-optimism-txpool.workspace = true
reth-rpc-server-types.workspace = true
reth-optimism-storage.workspace = true
reth-transaction-pool.workspace = true
reth-optimism-chainspec.workspace = true
reth-optimism-primitives.workspace = true
reth-optimism-payload-builder.workspace = true
reth-db.workspace = true
reth-ipc = { workspace = true, optional = true }
reth-tasks = { workspace = true, optional = true }
reth-chainspec = { workspace = true, optional = true }
reth-node-core = { workspace = true, optional = true }
reth-rpc-layer = { workspace = true, optional = true }
reth-primitives-traits = { workspace = true, optional = true }

# alloy
alloy-eips = { workspace = true, optional = true, features = ["std"] }
alloy-signer = { workspace = true, optional = true }
alloy-genesis = { workspace = true, optional = true, features = ["std"] }
alloy-provider = { workspace = true, optional = true }
alloy-rpc-types = { workspace = true, optional = true }
alloy-primitives = { workspace = true, optional = true }
alloy-rpc-client = { workspace = true, optional = true }
alloy-rpc-types-engine = { workspace = true, optional = true, features = ["std"] }

# base-alloy
base-alloy-network = { workspace = true, optional = true }
base-alloy-rpc-types-engine = { workspace = true, optional = true }

# tokio
tokio.workspace = true

# rpc
jsonrpsee = { workspace = true, optional = true }

# misc
serde = { workspace = true, features = ["std"] }
eyre.workspace = true
tracing = { workspace = true, features = ["std"] }
futures-util.workspace = true
url = { workspace = true, optional = true }
tower = { workspace = true, optional = true }
chrono = { workspace = true, optional = true }

tracing-subscriber = { workspace = true, optional = true }
