name = "Base"
public_rpc = "https://mainnet.base.org"
sequencer_rpc = "https://mainnet-sequencer.base.org"
explorer = "https://explorer.base.org"
superchain_level = 1
governed_by_optimism = false
superchain_time = 0
data_availability_type = "eth-da"
chain_id = 8453
batch_inbox_addr = "0xFf00000000000000000000000000000000008453"
block_time = 2
seq_window_size = 3600
max_sequencer_drift = 600

[hardforks]
  canyon_time = 1704992401 # Thu 11 Jan 2024 17:00:01 UTC
  delta_time = 1708560000 # Thu 22 Feb 2024 00:00:00 UTC
  ecotone_time = 1710374401 # Thu 14 Mar 2024 00:00:01 UTC
  fjord_time = 1720627201 # Wed 10 Jul 2024 16:00:01 UTC
  granite_time = 1726070401 # Wed 11 Sep 2024 16:00:01 UTC
  holocene_time = 1736445601 # Thu 9 Jan 2025 18:00:01 UTC
  isthmus_time = 1746806401 # Fri 9 May 2025 16:00:01 UTC
  jovian_time = 1764691201 # Tue 2 Dec 2025 16:00:01 UTC

[optimism]
  eip1559_elasticity = 6
  eip1559_denominator = 50
  eip1559_denominator_canyon = 250

[genesis]
  l2_time = 1686789347
  [genesis.l1]
    hash = "0x5c13d307623a926cd31415036c8b7fa14572f9dac64528e857a470511fc30771"
    number = 17481768
  [genesis.l2]
    hash = "0xf712aa9241cc24369b143cf6dce85f0902a9731e70d66818a3a5845b296c73dd"
    number = 0
  [genesis.system_config]
    batcherAddress = "0x5050F69a9786F081509234F1a7F4684b5E5b76C9"
    overhead = "0x00000000000000000000000000000000000000000000000000000000000000bc"
    scalar = "0x00000000000000000000000000000000000000000000000000000000000a6fe0"
    gasLimit = 30000000

[roles]
  ProxyAdminOwner = "0x7bB41C3008B3f03FE483B28b8DB90e19Cf07595c"

[addresses]
  L1StandardBridgeProxy = "0x3154Cf16ccdb4C6d922629664174b904d80F2C35"
  OptimismPortalProxy = "0x49048044D57e1C92A77f79988d21Fa8fAF74E97e"
  SystemConfigProxy = "0x73a79Fab69143498Ed3712e519A88a918e1f4072"
  DisputeGameFactoryProxy = "0x43edB88C4B80fDD2AdFF2412A7BebF9dF42cB40e"
