name = "Mainnet"
protocol_versions_addr = "0x8062AbC286f5e7D9428a0Ccb9AbD71e50d93b935"
superchain_config_addr = "0x95703e0982140D16f8ebA6d158FccEde42f04a4C"

[hardforks]
canyon_time =  1704992401 # Thu 11 Jan 2024 17:00:01 UTC
delta_time =   1708560000 # Thu 22 Feb 2024 00:00:00 UTC
ecotone_time = 1710374401 # Thu 14 Mar 2024 00:00:01 UTC
fjord_time =   1720627201 # Wed 10 Jul 2024 16:00:01 UTC
granite_time = 1726070401 # Wed 11 Sep 2024 16:00:01 UTC
holocene_time = 1736445601 # Thu 9 Jan 2025 18:00:01 UTC
isthmus_time = 1746806401 # Fri 9 May 2025 16:00:01 UTC
jovian_time = 1764691201 # Tue 2 Dec 2025 16:00:01 UTC

[l1]
  chain_id = 1
  public_rpc = "https://ethereum-rpc.publicnode.com"
  explorer = "https://eth.blockscout.com"
