[package]
name = "flashblocks-e2e"
description = "End-to-end regression testing tool for node-reth flashblocks RPC"

version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[lints]
workspace = true

[dependencies]
# internal
base-testing-flashblocks-e2e.workspace = true

# alloy
alloy-primitives.workspace = true

# misc
clap = { workspace = true, features = ["derive"] }
dotenvy.workspace = true
eyre.workspace = true
tokio = { workspace = true, features = ["full"] }
tracing.workspace = true
tracing-subscriber = { workspace = true, features = ["env-filter"] }
