[package]
name = "base-alloy-hardforks"
description = "Named bindings for hardforks"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
exclude.workspace = true

[lints]
workspace = true

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[dependencies]
# alloy
alloy-chains.workspace = true
alloy-primitives.workspace = true
alloy-hardforks.workspace = true

# misc
auto_impl.workspace = true
serde = { workspace = true, optional = true }

[features]
serde = [
	"alloy-chains/serde",
	"alloy-hardforks/serde",
	"alloy-primitives/serde",
	"dep:serde",
]
