[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
test = 'test'
cache_path = 'cache'
solc_version = '0.8.23'
optimizer = true
optimizer_runs = 1000000
evm_version = 'paris'

remappings = [
    '@account-abstraction/=lib/account-abstraction/contracts/',
    '@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/',
]

