[workspace]
resolver = "2"
members = ["op-enclave-core", "op-enclave-server", "op-enclave-client"]

[workspace.package]
version = "0.1.0"
edition = "2024"
rust-version = "1.88"

[workspace.dependencies]
alloy-chains = "0.2"
alloy-eips = { version = "1.4", features = ["serde"] }
alloy-primitives = { version = "1.5", features = ["serde"] }
alloy-consensus = { version = "1.6", features = ["serde"] }
alloy-rlp = "0.3"
alloy-trie = "0.9"
kona-genesis = { version = "0.4", features = ["serde"] }
op-alloy-consensus = { version = "0.23.1", features = ["serde"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
hex = { version = "0.4.3", features = ["serde"] }
thiserror = "2.0"
op-enclave-core = { path = "op-enclave-core" }

[workspace.lints.rust]
missing-debug-implementations = "warn"
missing-docs = "warn"
unreachable-pub = "warn"
unused-must-use = "deny"
rust-2018-idioms = "deny"

[workspace.lints.clippy]
all = { level = "warn", priority = -1 }
missing-const-for-fn = "warn"
redundant-clone = "warn"
use-self = "warn"
uninlined-format-args = "warn"
undocumented-unsafe-blocks = "warn"
derive-partial-eq-without-eq = "warn"
