[workspace]
resolver = "2"
members = ["op-enclave-core", "op-enclave-server", "op-enclave-client"]

[workspace.package]
version = "0.1.0"
edition = "2024"
rust-version = "1.88"

[workspace.dependencies]
alloy-chains = "0.2"
alloy-eips = { version = "1.4", features = ["serde"] }
alloy-primitives = { version = "1.5", features = ["serde"] }
alloy-consensus = { version = "1.6", features = ["serde"] }
alloy-rlp = "0.3"
alloy-trie = "0.9"
kona-genesis = { git = "https://github.com/ethereum-optimism/optimism", rev = "238012d2d96d5cebbdc390c9199bd63722115a42", default-features = false, features = ["serde"] }
op-alloy-consensus = { version = "0.23.1", features = ["serde"] }
kona-protocol = { git = "https://github.com/ethereum-optimism/optimism", rev = "238012d2d96d5cebbdc390c9199bd63722115a42", default-features = false, features = ["serde"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
hex = { version = "0.4.3", features = ["serde"] }
thiserror = "2.0"
op-enclave-core = { path = "op-enclave-core" }
op-enclave-server = { path = "op-enclave-server" }

# NSM and Attestation
aws-nitro-enclaves-nsm-api = "0.4"
aws-nitro-enclaves-cose = "0.5"

# Cryptography
rsa = { version = "0.9", features = ["sha2"] }
k256 = { version = "0.13", features = ["ecdsa", "arithmetic"] }
alloy-signer-local = "1.4"
sha2 = "0.10"
rand = "0.8"

# X.509 and PKIX
spki = "0.7"
x509-cert = "0.2"
openssl = "0.10"

# Encoding
zip = "2.2"
base64 = "0.22"
ciborium = "0.2"
serde_bytes = "0.11"

# Logging
tracing = "0.1"

# Async
parking_lot = "0.12"
tokio = { version = "1.0", features = ["full", "process"] }
reqwest = { version = "0.12", features = ["json", "blocking"] }

[workspace.lints.rust]
missing-debug-implementations = "warn"
missing-docs = "warn"
unreachable-pub = "warn"
unused-must-use = "deny"
rust-2018-idioms = "deny"

[workspace.lints.clippy]
all = { level = "warn", priority = -1 }
missing-const-for-fn = "warn"
redundant-clone = "warn"
use-self = "warn"
uninlined-format-args = "warn"
undocumented-unsafe-blocks = "warn"
derive-partial-eq-without-eq = "warn"
