[package]
name = "kona-mpt"
description = "Utilities for interacting with and iterating through a merkle patricia trie"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true

[lints]
workspace = true

[dependencies]
# General
thiserror.workspace = true
serde = { workspace = true, optional = true, features = ["derive", "alloc"] }

# Revm + Alloy
alloy-rlp.workspace = true
alloy-trie.workspace = true
alloy-primitives = { workspace = true, features = ["rlp"] }

# Base Alloy
base-alloy-rpc-types-engine.workspace = true

[dev-dependencies]
# Alloy
alloy-consensus.workspace = true
alloy-transport-http.workspace = true
alloy-provider = { workspace = true, features = ["reqwest"] }
alloy-rpc-types = { workspace = true, features = ["eth", "debug"] }

# General
rand.workspace = true
reqwest.workspace = true
proptest.workspace = true
tokio = { workspace = true, features = ["full"] }

[features]
default = [ "serde" ]
serde = [
	"alloy-primitives/serde",
	"alloy-trie/serde",
	"base-alloy-rpc-types-engine/serde",
	"dep:serde",
]
