[package]
name = "base-execution-storage"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[lints]
workspace = true

[dependencies]
# reth
base-execution-primitives = { workspace = true, features = ["serde", "reth-codec"] }
reth-storage-api = { workspace = true, features = ["db-api"] }

# ethereum
alloy-consensus.workspace = true

[dev-dependencies]
reth-codecs = { workspace = true, features = ["test-utils"] }
reth-prune-types.workspace = true
reth-stages-types.workspace = true

[features]
default = [ "std" ]
std = [
	"alloy-consensus/std",
	"base-execution-primitives/std",
	"reth-prune-types/std",
	"reth-stages-types/std",
	"reth-storage-api/std",
]
