[package]
name = "reth-optimism-chainspec"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
description = "EVM chain spec implementation for optimism."

[lints]
workspace = true

[dependencies]
# reth
reth-chainspec.workspace = true
reth-ethereum-forks.workspace = true
reth-primitives-traits.workspace = true
reth-network-peers.workspace = true

# op-reth
reth-optimism-forks.workspace = true
reth-optimism-primitives.workspace = true

# ethereum
alloy-chains.workspace = true
alloy-genesis.workspace = true
alloy-primitives.workspace = true
alloy-consensus.workspace = true
alloy-eips.workspace = true
alloy-hardforks.workspace = true

# op
op-alloy-rpc-types.workspace = true

serde = { workspace = true, optional = true }
serde_json.workspace = true

# misc
derive_more.workspace = true
op-alloy-consensus.workspace = true

[dev-dependencies]
reth-chainspec = { workspace = true, features = ["test-utils"] }
alloy-op-hardforks.workspace = true

[features]
default = [ "std" ]
std = [
	"alloy-chains/std",
	"alloy-consensus/std",
	"alloy-eips/std",
	"alloy-genesis/std",
	"alloy-primitives/std",
	"derive_more/std",
	"op-alloy-consensus/std",
	"op-alloy-rpc-types/std",
	"reth-chainspec/std",
	"reth-ethereum-forks/std",
	"reth-network-peers/std",
	"reth-optimism-forks/std",
	"reth-optimism-primitives/std",
	"reth-primitives-traits/std",
	"serde?/std",
	"serde_json/std",
]
serde = [
	"alloy-chains/serde",
	"alloy-consensus/serde",
	"alloy-eips/serde",
	"alloy-hardforks/serde",
	"alloy-op-hardforks/serde",
	"alloy-primitives/serde",
	"op-alloy-consensus/serde",
	"op-alloy-rpc-types/serde",
	"reth-ethereum-forks/serde",
	"reth-optimism-forks/serde",
	"reth-optimism-primitives/serde",
	"reth-primitives-traits/serde",
]
