[package]
name = "websocket-proxy-bin"
description = "WebSocket Proxy Binary"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
[[bin]]
name = "websocket-proxy"
path = "src/main.rs"

[lints]
workspace = true

[dependencies]
anyhow.workspace = true
serde.workspace = true
hostname.workspace = true
dotenvy.workspace = true
tracing = { workspace = true, features = ["std"] }
websocket-proxy.workspace = true
base-cli-utils.workspace = true
tokio = { workspace = true, features = ["full"] }
axum = { workspace = true, features = ["ws"] }
clap = { workspace = true, features = ["derive", "env"] }
