[package]
name = "based-bin"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "based"
path = "src/main.rs"

[lints]
workspace = true

[dependencies]
clap = { workspace = true }
based = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
tokio = { workspace = true }
cadence = { workspace = true }
