[package]
name = "based-bin"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "based"
path = "src/main.rs"

[lints]
workspace = true

[dependencies]
clap = { workspace = true }
serde = { workspace = true }
based = { workspace = true }
anyhow = { workspace = true }
tokio = { workspace = true }
base-cli-utils = { workspace = true }
