[package]
name = "base-access-lists"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
description = "FBAL library crate"

[lints]
workspace = true

[dependencies]
alloy-primitives.workspace = true
alloy-eip7928 = {workspace = true, features = ["serde", "rlp"]}
alloy-rlp = {workspace = true, features = ["derive"]}
tracing.workspace = true
revm.workspace = true
serde.workspace = true

[dev-dependencies]
op-revm.workspace = true
eyre.workspace = true
reth-optimism-evm.workspace = true
reth-optimism-chainspec.workspace = true
alloy-consensus.workspace = true
alloy-contract.workspace = true
alloy-sol-types.workspace = true
reth-evm.workspace = true
base-primitives = { workspace = true, features = ["test-utils"] }

[[test]]
name = "builder"
path = "tests/builder/main.rs"
