[package]
name = "base-consensus-cli"
version.workspace = true
description = "Shared CLI utilities for Base consensus crates"
edition.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true

[lints]
workspace = true

[dependencies]
# Workspace
base-consensus-genesis.workspace = true
base-consensus-registry.workspace = true
base-cli-utils.workspace = true

# Alloy
alloy-primitives.workspace = true

# General
thiserror = { workspace = true, features = ["std"] }
clap = { workspace = true, features = ["derive", "env"] }

# `secrets` feature
tracing = { workspace = true, features = ["std"], optional = true }
libp2p = { workspace = true, features = ["secp256k1"], optional = true }

[dev-dependencies]
base-consensus-registry.workspace = true

[features]
default = []
secrets = [ "dep:libp2p", "dep:tracing" ]
