[package]
name = "base-consensus-cli"
version.workspace = true
description = "Shared CLI utilities for Kona crates"
edition.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true

[lints]
workspace = true

[dependencies]
# Workspace
base-consensus-genesis.workspace = true
base-consensus-registry.workspace = true
base-cli-utils.workspace = true

# Alloy
alloy-chains = { workspace = true, features = ["std"] }

# General
clap = { workspace = true, features = ["derive", "env"] }
thiserror = { workspace = true, features = ["std"] }

# `secrets` feature
tracing = { workspace = true, features = ["std"], optional = true }
libp2p = { workspace = true, features = ["secp256k1"], optional = true }
alloy-primitives.workspace = true

[dev-dependencies]
rstest.workspace = true

[features]
default = []
secrets = [ "dep:libp2p", "dep:tracing" ]
