[package]
name = "kona-cli"
version.workspace = true
description = "Shared CLI utilities for Kona crates"
edition.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true

[lints]
workspace = true

[dependencies]
# Workspace
kona-genesis.workspace = true
kona-registry.workspace = true
base-cli-utils.workspace = true

# Alloy
alloy-chains = { workspace = true, features = ["std"] }

# General
tracing = { workspace = true, features = ["std"] }
serde = { workspace = true, features = ["derive", "std"]}
clap = { workspace = true, features = ["derive", "env"] }
tracing-subscriber = { workspace = true, features = ["fmt", "env-filter", "json", "tracing-log"] }
tracing-appender.workspace = true
thiserror = { workspace = true, features = ["std"] }

# `secrets` feature
libp2p = { workspace = true, features = ["secp256k1"], optional = true }
alloy-primitives.workspace = true

[dev-dependencies]
rstest.workspace = true

[target.'cfg(unix)'.dependencies]
libc = "0.2"

[features]
default = []
secrets = [ "dep:libp2p" ]
