[package]
name = "basectl-cli"
version.workspace = true
edition.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
dirs = { workspace = true }
tokio = { workspace = true }
serde = { workspace = true }
chrono = { workspace = true }
anyhow = { workspace = true }
ratatui = { workspace = true }
arboard = { workspace = true }
tracing = { workspace = true }
crossterm = { workspace = true }
base-primitives.workspace = true
serde_json = { workspace = true }
serde_yaml = { workspace = true }
alloy-eips = { workspace = true }
futures-util = { workspace = true }
alloy-contract = { workspace = true }
alloy-sol-types = { workspace = true }
op-alloy-network = { workspace = true }
alloy-primitives = { workspace = true }
tokio-tungstenite = { workspace = true, features = ["rustls-tls-webpki-roots"] }
op-alloy-consensus = { workspace = true }
alloy-rpc-types-eth = { workspace = true }
url = { workspace = true, features = ["serde"] }
alloy-provider = { workspace = true, features = ["pubsub", "ws"] }
