[package]
name = "base-protocol"
description = "Protocol Types"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[lints]
workspace = true

[features]
default = ["std"]
std = [
    "alloy-primitives/std",
    "alloy-consensus/std",
    "alloy-eips/std",
]
serde = [
    "dep:serde",
    "dep:serde_json",
    "alloy-primitives/serde",
    "alloy-consensus/serde",
    "alloy-eips/serde",
]
arbitrary = ["dep:arbitrary"]

[dependencies]
# Alloy
alloy-primitives.workspace = true
alloy-consensus.workspace = true
alloy-eips.workspace = true
alloy-rpc-types-eth.workspace = true

# op-alloy
op-alloy-rpc-types-engine.workspace = true

# General
derive_more = { workspace = true, features = ["display"] }
thiserror.workspace = true

# Optional
serde = { workspace = true, optional = true }
serde_json = { workspace = true, optional = true }
arbitrary = { version = "1", optional = true }

[dev-dependencies]
op-alloy-consensus.workspace = true
serde_json.workspace = true
rand.workspace = true
