[package]
name = "base-protocol"
description = "Protocol Types"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[lints]
workspace = true

[dependencies]
# workspace
kona-genesis.workspace = true

# alloy
alloy-rlp.workspace = true
alloy-eips.workspace = true
alloy-consensus.workspace = true
alloy-rpc-types-eth.workspace = true
alloy-rpc-types-engine.workspace = true
alloy-primitives = { workspace = true, features = ["map"] }

# base-alloy
base-alloy-consensus.workspace = true
base-alloy-rpc-types-engine.workspace = true

# misc
tracing.workspace = true
thiserror.workspace = true
ambassador = "0.4.2"
async-trait.workspace = true
unsigned-varint.workspace = true
derive_more = { workspace = true, features = ["display"] }

# compression
brotli.workspace = true
miniz_oxide.workspace = true
alloc-no-stdlib.workspace = true

# optional
serde = { workspace = true, optional = true }
arbitrary = { workspace = true, features = ["derive"], optional = true }
spin = { workspace = true, optional = true }
tracing-subscriber = { workspace = true, features = ["fmt"], optional = true }

[dev-dependencies]
spin.workspace = true
rstest.workspace = true
proptest.workspace = true
serde_json.workspace = true
alloy-sol-types.workspace = true
kona-registry.workspace = true
base-alloy-consensus.workspace = true
base-alloy-rpc-types.workspace = true
alloy-rpc-types-eth.workspace = true
brotli = { workspace = true, features = ["std"] }
tokio = { workspace = true, features = ["full"] }
arbitrary = { workspace = true, features = ["derive"] }
tracing-subscriber = { workspace = true, features = ["fmt"] }
alloy-primitives = { workspace = true, features = ["arbitrary"] }
rand = { workspace = true, features = ["std", "std_rng"] }

[features]
default = [ "std" ]
test-utils = [ "dep:spin", "dep:tracing-subscriber" ]
std = [
	"alloy-consensus/std",
	"alloy-eips/std",
	"alloy-primitives/std",
	"alloy-rlp/std",
	"alloy-rpc-types-engine/std",
	"alloy-rpc-types-eth/std",
	"base-alloy-consensus/std",
	"base-alloy-rpc-types-engine/std",
	"brotli/std",
	"derive_more/std",
	"kona-genesis/std",
	"miniz_oxide/std",
	"serde?/std",
	"spin?/std",
	"thiserror/std",
	"tracing/std",
	"unsigned-varint/std",
]
serde = [
	"alloy-consensus/serde",
	"alloy-eips/serde",
	"alloy-primitives/serde",
	"alloy-rpc-types-engine/serde",
	"alloy-rpc-types-eth/serde",
	"base-alloy-consensus/serde",
	"base-alloy-rpc-types-engine/serde",
	"dep:serde",
	"kona-genesis/serde",
	"miniz_oxide/serde",
	"tracing-subscriber?/serde",
]
arbitrary = [
	"alloy-consensus/arbitrary",
	"alloy-eips/arbitrary",
	"alloy-primitives/arbitrary",
	"alloy-primitives/rand",
	"alloy-rpc-types-engine/arbitrary",
	"alloy-rpc-types-eth/arbitrary",
	"base-alloy-consensus/arbitrary",
	"base-alloy-rpc-types-engine/arbitrary",
	"dep:arbitrary",
	"kona-genesis/arbitrary",
	"std",
]
