[package]
name = "base-rpc"
description = "RPC Types and Client for Base"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[lints]
workspace = true

[dependencies]
# workspace
base-protocol = { workspace = true, features = ["serde"] }

# rpc
jsonrpsee = { workspace = true, features = ["macros", "server"] }

[features]
default = [ "std" ]
std = [ "base-protocol/std" ]
client = [
	"jsonrpsee/async-client",
	"jsonrpsee/client",
	"jsonrpsee/http-client",
]
