[package]
name = "base-consensus-rpc"
description = "RPC Types and Client for Base"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[lints]
workspace = true

[dependencies]
# Workspace
kona-gossip.workspace = true
kona-engine.workspace = true
kona-macros.workspace = true
kona-genesis = { workspace = true, features = ["serde", "std"] }
base-protocol = { workspace = true, features = ["serde", "std"] }

# OP Alloy
op-alloy-rpc-jsonrpsee.workspace = true
op-alloy-rpc-types-engine = { workspace = true, features = ["serde", "std"] }

# Alloy
alloy-eips = { workspace = true, features = ["serde", "std"] }
alloy-primitives = { workspace = true, features = ["map", "rlp", "serde", "std"] }

# Misc
ipnet.workspace = true
backon.workspace = true
libp2p.workspace = true
tracing = { workspace = true, features = ["std"] }
thiserror = { workspace = true, features = ["std"] }
async-trait.workspace = true
rollup-boost.workspace = true
tokio = { workspace = true, features = ["time"] }
serde = { workspace = true, features = ["std"] }

# RPC
jsonrpsee = { workspace = true, features = ["macros", "server"] }
getrandom = { workspace = true, features = ["wasm_js"] }

# Optional
metrics = { workspace = true, optional = true }

[dev-dependencies]
serde_json = { workspace = true, features = ["std"] }

[features]
default = []
reqwest = [ "client" ]
client = [
	"jsonrpsee/async-client",
	"jsonrpsee/client",
	"jsonrpsee/http-client",
	"op-alloy-rpc-jsonrpsee/client",
]
metrics = [
	"dep:metrics",
	"kona-engine/metrics",
	"kona-gossip/metrics",
	"libp2p/metrics",
]
