[package]
name = "base-account-abstraction"
description = "Base account abstraction types"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[lints]
workspace = true

[dependencies]
alloy-primitives = { workspace = true, features = ["map-foldhash", "serde"] }
alloy-rpc-types = { workspace = true, features = ["eth"] }
alloy-sol-types.workspace = true
anyhow = { workspace = true, features = ["std"] }
async-trait.workspace = true
serde = { workspace = true, features = ["std", "derive"] }

[dev-dependencies]
serde_json = { workspace = true, features = ["std"] }
