global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'l2_builder'
    static_configs:
      - targets: ['base-builder:7090']

  - job_name: 'l2_builder_cl'
    static_configs:
      - targets: ['base-builder-cl:7300']

  - job_name: 'l2_client'
    static_configs:
      - targets: ['base-client:8090']

  - job_name: 'l2_client_cl'
    static_configs:
      - targets: ['base-client-cl:8300']

  - job_name: 'batcher'
    static_configs:
      - targets: ['op-batcher:6060']
